import { Platform, StyleSheet } from 'react-native';

import { LAYOUT } from '@/constants/layout';
import { DESIGN_TOKENS } from '@/constants/designSystem';
import type { ThemedColors } from '@/hooks/useTheme';
import { webTextStyle, webViewStyle } from '@/utils/webProps';
const SCROLL_BOTTOM_RESERVE = Platform.select({
  web: 'calc(var(--mt-dock-h, 0px) + 24px)' as unknown as number,
  default: (LAYOUT?.tabBarHeight ?? 56) + DESIGN_TOKENS.spacing.xl,
});
export const createStyles = (colors: ThemedColors, isMobile: boolean) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: colors.background },
    content: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: SCROLL_BOTTOM_RESERVE,
      alignItems: 'center',
    },
    inner: { width: '100%', maxWidth: 860, gap: 14 },
    loader: { marginVertical: 48 },
    error: { color: colors.danger, fontSize: 14, fontWeight: '600', marginVertical: 24 },
    cover: {
      overflow: 'hidden',
      borderRadius: 12,
      backgroundColor: colors.surfaceMuted,
    },
    header: { gap: 6 },
    badgeRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 6 },
    badge: {
      alignSelf: 'flex-start',
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    badgeText: { fontSize: 12, fontWeight: '700', color: colors.textOnDark },
    metaChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 4,
      backgroundColor: colors.surfaceMuted,
    },
    metaChipText: { fontSize: 12, fontWeight: '600', color: colors.textSecondary },
    title: { fontSize: isMobile ? 20 : 24, fontWeight: '900', color: colors.text },
    meta: { fontSize: 14, color: colors.textSecondary },
    summaryPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      alignSelf: 'flex-start',
      maxWidth: '100%',
      marginTop: 2,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.surface,
    },
    summaryPillWarning: {
      borderColor: colors.warningLight,
      backgroundColor: colors.warningSoft,
    },
    summaryPillText: { fontSize: 13, fontWeight: '700', color: colors.text, flexShrink: 1 },
    summaryPillTextWarning: { color: colors.warningDark },
    approximateNote: { fontSize: 12, lineHeight: 16, color: colors.warningDark, fontWeight: '600' },
    description: { fontSize: 15, color: colors.text, lineHeight: 21, marginTop: 4 },
    descriptionLink: { color: colors.primaryDark, fontWeight: '700' },
    ownerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    deleteError: { fontSize: 13, lineHeight: 18, color: colors.danger, fontWeight: '600' },
    editPanel: {
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surface,
    },
    editHeading: { fontSize: 18, fontWeight: '800', color: colors.text },
    label: { fontSize: 13, fontWeight: '700', color: colors.text, marginTop: 2 },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      backgroundColor: colors.surface,
      fontSize: 14,
      ...Platform.select({ web: webTextStyle({ outlineWidth: 0 }) }),
    },
    textArea: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      backgroundColor: colors.surface,
      fontSize: 14,
      minHeight: 110,
      textAlignVertical: 'top',
      ...Platform.select({ web: webTextStyle({ outlineWidth: 0 }) }),
    },
    coverUpload: { gap: 6 },
    coverUploadHint: { fontSize: 12, lineHeight: 17, color: colors.textMuted },
    formRow: { flexDirection: 'row', gap: 10 },
    formCol: { flex: 1, gap: 6 },
    datePickerTrigger: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      minHeight: Platform.OS === 'android' ? 48 : 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    datePickerText: { flex: 1, color: colors.text, fontSize: 14, fontWeight: '600' },
    datePickerOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
      padding: 16,
    },
    datePickerSheet: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      gap: 12,
    },
    datePickerHeader: { gap: 6 },
    datePickerTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    datePickerTitle: { fontSize: 18, fontWeight: '700', color: colors.text },
    datePickerHint: { fontSize: 12, color: colors.textMuted, lineHeight: 16 },
    datePickerCalendar: { marginHorizontal: -16 },
    optionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    editActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
    editError: { fontSize: 13, lineHeight: 18, color: colors.danger, fontWeight: '600' },
    tabBar: {
      flexDirection: 'row',
      gap: 6,
      padding: 4,
      borderRadius: 14,
      backgroundColor: colors.surfaceMuted,
    },
    tab: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      minHeight: 40,
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderRadius: 10,
    },
    tabActive: {
      backgroundColor: colors.surface,
      ...Platform.select({
        web: webViewStyle({ boxShadow: DESIGN_TOKENS.shadows.light }),
        default: DESIGN_TOKENS.shadowsNative.light,
      }),
    },
    tabText: { fontSize: 13, fontWeight: '700', color: colors.textSecondary },
    tabTextActive: { color: colors.primaryDark },
    panel: {
      gap: 16,
    },
    panelHint: { fontSize: 14, lineHeight: 20, color: colors.textMuted },
  });
