import { Platform, StyleSheet } from 'react-native';
import type { ThemedColors } from '@/hooks/useTheme';
import { webTextStyle } from '@/utils/webProps';
export const createStyles = (colors: ThemedColors) =>
  StyleSheet.create({
    wrap: { gap: 12 },
    heading: { fontSize: 18, fontWeight: '700', color: colors.text },
    label: { fontSize: 14, fontWeight: '600', color: colors.text, marginTop: 4 },
    hint: { fontSize: 13, color: colors.textMuted, lineHeight: 18 },
    errorText: { fontSize: 13, color: colors.danger, lineHeight: 18 },
    pointList: { gap: 8 },
    pointRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surface,
    },
    pointIcon: { width: 22, alignItems: 'center', paddingTop: 1 },
    pointBody: { flex: 1, gap: 2 },
    pointType: { fontSize: 11, color: colors.textMuted, fontWeight: '600' },
    pointName: { fontSize: 15, fontWeight: '600', color: colors.text },
    pointDescription: { fontSize: 13, color: colors.textSecondary, lineHeight: 18 },
    descriptionLink: { color: colors.primaryDark, fontWeight: '700' },
    pointCoordinates: { fontSize: 12, color: colors.textMuted, lineHeight: 16 },
    pointControls: { flexDirection: 'row', gap: 4 },
    ctrl: {
      width: 32,
      height: 32,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceMuted,
    },
    ctrlDisabled: { opacity: 0.4 },
    addForm: {
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surfaceMuted,
    },
    editForm: {
      gap: 8,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surface,
    },
    editActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    typeChip: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 6,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    typeChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    typeChipText: { fontSize: 13, color: colors.text },
    typeChipTextActive: { color: colors.textOnPrimary, fontWeight: '600' },
    input: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      color: colors.text,
      backgroundColor: colors.surface,
      fontSize: 14,
      ...Platform.select({ web: webTextStyle({ outlineWidth: 0 }) }),
    },
    coordRow: { flexDirection: 'row', gap: 8 },
    coordInput: { flex: 1 },
    siteSearch: { gap: 8 },
    siteResults: { gap: 6 },
    siteOption: {
      minHeight: 68,
      paddingVertical: 7,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    siteOptionImage: {
      width: 72,
      height: 54,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: colors.surface,
      flexShrink: 0,
    },
    siteOptionBody: { flex: 1, minWidth: 0, gap: 1 },
    siteOptionKind: { fontSize: 11, color: colors.textMuted, fontWeight: '700' },
    siteOptionTitle: { fontSize: 14, color: colors.text, fontWeight: '700' },
    siteOptionSubtitle: { fontSize: 12, color: colors.textSecondary },
    templates: { gap: 8 },
    templateRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surface,
    },
    templateBody: { flex: 1, gap: 2 },
    templateTitle: { fontSize: 14, fontWeight: '600', color: colors.text },
    templateDescription: { fontSize: 12, color: colors.textMuted, lineHeight: 16 },
  });
