import { Platform, StyleSheet } from 'react-native'
import { DESIGN_TOKENS } from '@/constants/designSystem'
import type { useThemedColors } from '@/hooks/useTheme'

export const createStyles = (colors: ReturnType<typeof useThemedColors>) => StyleSheet.create({
  container: {
    flexDirection: 'column',
    backgroundColor: colors.surface,
    borderRadius: DESIGN_TOKENS.radii.lg,
    marginHorizontal: DESIGN_TOKENS.spacing.md,
    marginBottom: DESIGN_TOKENS.spacing.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...(Platform.OS === 'web' ? ({
      boxShadow: colors.boxShadows.light,
      transition: 'transform 200ms ease-out, box-shadow 200ms ease-out, border-color 200ms ease',
      cursor: 'pointer',
    } as any) : null),
  },
  containerCompact: {
    marginHorizontal: 0,
  },
  containerActive: {
    borderColor: colors.primary,
    borderWidth: 2,
    backgroundColor: colors.primarySoft,
    ...(Platform.OS === 'web' ? ({ boxShadow: `0 0 0 3px ${colors.primaryAlpha30}, ${colors.boxShadows.hover}` } as any) : null),
  },
  containerGrid: {
    marginHorizontal: 0,
    marginBottom: 0,
    flex: 1,
    alignSelf: 'stretch',
  },
  colorIndicator: {
    position: 'absolute',
    top: DESIGN_TOKENS.spacing.sm,
    left: DESIGN_TOKENS.spacing.sm,
    width: 10,
    height: 10,
    borderRadius: DESIGN_TOKENS.radii.pill,
    zIndex: 2,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.9)',
    ...(Platform.OS === 'web' ? ({ boxShadow: colors.boxShadows.light } as any) : null),
  },
  photoWrap: {
    width: '100%',
    height: 140,
    position: 'relative',
  },
  photoWrapGrid: {
    width: '100%',
    height: 160,
  },
  contentContainer: {
    padding: 0,
  },
  content: {
    flex: 1,
    padding: DESIGN_TOKENS.spacing.md,
    paddingTop: DESIGN_TOKENS.spacing.sm,
  },
  contentSelectionMode: {
    paddingRight: DESIGN_TOKENS.spacing.md + 40,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 4,
  },
  headerRowNarrow: {
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 4,
  },
  headerMain: {
    flex: 1,
    minWidth: 0,
  },
  headerMainNarrow: {
    width: '100%',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 4,
    flexShrink: 0,
    ...(Platform.OS === 'web' ? ({
      opacity: 0,
      transition: 'opacity 150ms ease',
    } as any) : null),
  },
  headerActionsNarrow: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  webActionButton: {
    width: 32,
    height: 32,
    borderRadius: DESIGN_TOKENS.radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.backgroundSecondary,
    ...(Platform.OS === 'web' ? ({
      cursor: 'pointer',
      transition: 'background-color 150ms ease, transform 100ms ease',
    } as any) : null),
  },
  selectionBadge: {
    position: 'absolute',
    top: DESIGN_TOKENS.spacing.sm,
    right: DESIGN_TOKENS.spacing.sm,
    width: 32,
    height: 32,
    borderRadius: DESIGN_TOKENS.radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectionBadgeSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  selectionBadgeUnselected: {
    backgroundColor: colors.surface,
  },
  name: {
    fontSize: 17,
    fontWeight: '600' as any,
    color: colors.text,
    lineHeight: 22,
    letterSpacing: 0,
  },
  description: {
    fontSize: DESIGN_TOKENS.typography.sizes.sm,
    color: colors.textMuted,
    marginBottom: 6,
    lineHeight: 18,
  },
  metadata: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 8,
  },
  badge: {
    backgroundColor: colors.backgroundTertiary,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: DESIGN_TOKENS.radii.pill,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '500' as any,
    color: colors.textMuted,
    letterSpacing: 0,
  },
  address: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
    lineHeight: 18,
  },
  coordsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 8,
  },
  coordsBlock: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 6,
  },
  coordsSurface: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: DESIGN_TOKENS.radii.sm,
    backgroundColor: colors.backgroundSecondary,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  coordsSurfaceNarrow: {
    alignItems: 'flex-start',
  },
  coordsActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 4,
    flexShrink: 0,
  },
  coordsActionsRowNarrow: {
    width: '100%',
    justifyContent: 'flex-end',
  },
  coordsText: {
    fontSize: 12,
    fontFamily: Platform.OS === 'web' ? 'monospace' : undefined,
    color: colors.textMuted,
    flex: 1,
    minWidth: 0,
    opacity: 0.8,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickActionChip: {
    minWidth: 78,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: DESIGN_TOKENS.radii.sm,
    borderWidth: 1,
    borderColor: colors.borderLight,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    ...(Platform.OS === 'web' ? ({
      cursor: 'pointer',
      transition: 'transform 120ms ease, box-shadow 120ms ease, background-color 120ms ease',
      boxShadow: colors.boxShadows.light,
    } as any) : null),
  },
  quickActionChipPressed: {
    backgroundColor: colors.backgroundSecondary,
    ...(Platform.OS === 'web' ? ({
      transform: 'translateY(1px)',
      boxShadow: 'none',
    } as any) : null),
  },
  quickActionIconBubble: {
    width: 36,
    height: 36,
    borderRadius: DESIGN_TOKENS.radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabel: {
    fontSize: 12,
    lineHeight: 14,
    color: colors.text,
    fontWeight: '600' as any,
    textAlign: 'center',
  },
  rating: {
    fontSize: DESIGN_TOKENS.typography.sizes.sm,
    color: colors.textMuted,
  },
  driveInfoRow: {
    marginTop: 10,
    paddingTop: 10,
    paddingHorizontal: 12,
    paddingBottom: 10,
    marginHorizontal: -DESIGN_TOKENS.spacing.md,
    marginBottom: -DESIGN_TOKENS.spacing.md,
    backgroundColor: colors.primarySoft,
    borderTopWidth: 1,
    borderTopColor: colors.primaryAlpha30,
  },
  driveInfoText: {
    fontSize: 13,
    fontWeight: '500' as any,
    color: colors.primaryDark,
  },
  // Image overlay for category badge
  imageOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: DESIGN_TOKENS.spacing.sm,
    paddingVertical: 8,
    ...(Platform.OS === 'web' ? ({
      backgroundImage: 'linear-gradient(to top, rgba(0,0,0,0.5) 0%, transparent 100%)',
    } as any) : {
      backgroundColor: 'rgba(0,0,0,0.3)',
    }),
  },
  imageBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: DESIGN_TOKENS.radii.pill,
    ...(Platform.OS === 'web' ? ({
      backdropFilter: 'blur(8px)',
    } as any) : null),
  },
  imageBadgeText: {
    fontSize: 11,
    fontWeight: '600' as any,
    color: colors.text,
    letterSpacing: 0.3,
  },
})
