import { StyleSheet } from 'react-native'

import { DESIGN_TOKENS } from '@/constants/designSystem'
import type { ThemedColors } from '@/hooks/useTheme'

export const createRouteElevationProfileStyles = (colors: ThemedColors) =>
  StyleSheet.create({
    container: {
      marginTop: DESIGN_TOKENS.spacing.sm,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.surface,
      padding: DESIGN_TOKENS.spacing.md,
    },
    title: {
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      fontWeight: '700',
      color: colors.text,
    },
    subtitle: {
      marginTop: 2,
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '500',
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: DESIGN_TOKENS.spacing.sm,
      marginBottom: DESIGN_TOKENS.spacing.sm,
    },
    headerTextWrap: {
      flex: 1,
    },
    downloadBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    downloadBtnPressed: {
      opacity: 0.85,
      backgroundColor: colors.backgroundSecondary,
    },
    downloadBtnDisabled: {
      opacity: 0.45,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: DESIGN_TOKENS.spacing.xs,
      marginBottom: DESIGN_TOKENS.spacing.sm,
    },
    summaryCard: {
      minWidth: 124,
      flexGrow: 1,
      borderRadius: DESIGN_TOKENS.radii.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: DESIGN_TOKENS.spacing.sm,
      paddingVertical: DESIGN_TOKENS.spacing.sm,
    },
    summaryCardAccent: {
      backgroundColor: colors.backgroundSecondary,
      borderColor: colors.border,
    },
    summaryIconWrap: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      marginBottom: 8,
    },
    summaryIconWrapAccent: {
      backgroundColor: colors.primarySoft,
    },
    summaryLabel: {
      fontSize: 11,
      color: colors.textMuted,
      marginBottom: 2,
    },
    summaryValue: {
      fontSize: DESIGN_TOKENS.typography.sizes.xs,
      color: colors.text,
      fontWeight: '700',
    },
    chartWrap: {
      position: 'relative',
      borderRadius: DESIGN_TOKENS.radii.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.backgroundSecondary,
      overflow: 'hidden',
    },
    chartMetaRow: {
      position: 'absolute',
      top: DESIGN_TOKENS.spacing.xs,
      left: DESIGN_TOKENS.spacing.sm,
      right: DESIGN_TOKENS.spacing.sm,
      zIndex: 2,
      flexDirection: 'row',
      justifyContent: 'space-between',
      pointerEvents: 'none',
    },
    chartMetaBadge: {
      borderRadius: 999,
      backgroundColor: colors.surfaceAlpha40,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: DESIGN_TOKENS.spacing.xs,
      paddingVertical: 4,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    chartMetaBadgePeak: {
      backgroundColor: colors.primaryAlpha30,
      borderColor: colors.primaryAlpha40,
    },
    chartMetaBadgeCompact: {
      paddingHorizontal: 6,
      minHeight: 24,
    },
    chartMetaLabel: {
      fontSize: 11,
      color: colors.textMuted,
      fontWeight: '600',
    },
    chartMetaValue: {
      fontSize: 11,
      color: colors.text,
      fontWeight: '700',
    },
    tooltip: {
      position: 'absolute',
      zIndex: 3,
      width: 104,
      borderRadius: DESIGN_TOKENS.radii.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: DESIGN_TOKENS.spacing.xs,
      paddingVertical: 6,
    },
    tooltipTitle: {
      fontSize: 11,
      color: colors.text,
      fontWeight: '700',
      marginBottom: 2,
    },
    tooltipSubtitle: {
      fontSize: 10,
      color: colors.textMuted,
    },
    chartHitArea: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 4,
    },
    yAxisLabels: {
      position: 'absolute',
      top: 0,
      left: DESIGN_TOKENS.spacing.sm,
      width: 56,
      height: 120,
      zIndex: 1,
      pointerEvents: 'none',
    },
    yAxisText: {
      position: 'absolute',
      left: 0,
      fontSize: 10,
      color: colors.textMuted,
      backgroundColor: colors.surfaceAlpha40,
      paddingHorizontal: 4,
      borderRadius: 6,
      overflow: 'hidden',
    },
    yAxisTextCompact: {
      fontSize: 9,
      paddingHorizontal: 2,
    },
    axisLabels: {
      marginTop: 2,
      marginHorizontal: DESIGN_TOKENS.spacing.sm,
      marginBottom: DESIGN_TOKENS.spacing.xs,
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    axisText: {
      fontSize: 11,
      color: colors.textMuted,
    },
    tagsRow: {
      marginTop: 4,
      marginBottom: DESIGN_TOKENS.spacing.xs,
      marginHorizontal: DESIGN_TOKENS.spacing.sm,
      gap: DESIGN_TOKENS.spacing.xs,
    },
    pointCardsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: DESIGN_TOKENS.spacing.xs,
    },
    pointCardsGridCompact: {
      flexDirection: 'column',
    },
    pointCard: {
      minWidth: 150,
      flex: 1,
      borderRadius: DESIGN_TOKENS.radii.sm,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      padding: DESIGN_TOKENS.spacing.sm,
    },
    pointCardCompact: {
      minWidth: 0,
      flexBasis: '100%',
      paddingVertical: DESIGN_TOKENS.spacing.xs,
    },
    pointCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 6,
    },
    pointCardLabel: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '700',
    },
    pointCardValue: {
      fontSize: DESIGN_TOKENS.typography.sizes.md,
      color: colors.text,
      fontWeight: '700',
      marginBottom: 4,
    },
    pointCardCaption: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 16,
    },
    transportWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      paddingHorizontal: DESIGN_TOKENS.spacing.sm,
      paddingVertical: 6,
    },
    tagItem: {
      fontSize: DESIGN_TOKENS.typography.sizes.xs,
      color: colors.text,
      fontWeight: '600',
    },
  })
