/* global module, require */

const {
  AndroidConfig,
  withAndroidManifest,
  withAndroidStyles,
  withAppBuildGradle,
} = require('expo/config-plugins');

const GRADLE_CONFIG_MARKER = '// @generated by withAndroidReleaseSafety';
const MATERIAL_ANDROID_15_DEPENDENCY =
  'implementation("com.google.android.material:material:1.14.0")';

function patchMaterialDependency(contents) {
  const existingMaterialDependency =
    /implementation\(["']com\.google\.android\.material:material:[^"']+["']\)/;

  if (existingMaterialDependency.test(contents)) {
    return contents.replace(
      existingMaterialDependency,
      MATERIAL_ANDROID_15_DEPENDENCY,
    );
  }

  const reactAndroidDependency =
    /(^\s*implementation\(["']com\.facebook\.react:react-android["']\)\s*$)/m;
  if (!reactAndroidDependency.test(contents)) {
    throw new Error(
      'withAndroidReleaseSafety could not locate the react-android dependency',
    );
  }

  return contents.replace(
    reactAndroidDependency,
    `$1\n\n    // Material 1.14 guards system-bar APIs on Android 15+ (task #1060).\n    ${MATERIAL_ANDROID_15_DEPENDENCY}`,
  );
}

function patchBuildGradle(contents) {
  let next = patchMaterialDependency(contents);

  if (!next.includes(GRADLE_CONFIG_MARKER)) {
    next = next.replace(
      /(def projectRoot = .*\n)/,
      `$1\n${GRADLE_CONFIG_MARKER}\n` +
        `def appConfig = new groovy.json.JsonSlurper().parse(file("$projectRoot/app.json"))\n` +
        `def androidVersionCode = appConfig.expo.android.versionCode as Integer\n` +
        `def androidVersionName = appConfig.expo.version as String\n`,
    );
  }

  next = next
    .replace(/versionCode\s+\d+/, 'versionCode androidVersionCode')
    .replace(/versionName\s+"[^"]+"/, 'versionName androidVersionName');

  if (!next.includes('METRAVEL_ANDROID_KEYSTORE_PATH')) {
    const releaseSigningConfig = `        release {
            def keystorePath = System.getenv('METRAVEL_ANDROID_KEYSTORE_PATH')
            def keystorePassword = System.getenv('METRAVEL_ANDROID_KEYSTORE_PASSWORD')
            def keyAliasValue = System.getenv('METRAVEL_ANDROID_KEY_ALIAS')
            def keyPasswordValue = System.getenv('METRAVEL_ANDROID_KEY_PASSWORD')
            if (keystorePath && keystorePassword && keyAliasValue && keyPasswordValue) {
                storeFile file(keystorePath)
                storePassword keystorePassword
                keyAlias keyAliasValue
                keyPassword keyPasswordValue
            }
        }
`;

    next = next.replace(
      /(signingConfigs\s*\{\n)(\s*debug\s*\{)/,
      `$1${releaseSigningConfig}$2`,
    );
  }

  const buildTypesStart = next.indexOf('    buildTypes {');
  const packagingOptionsStart = next.indexOf(
    '    packagingOptions {',
    buildTypesStart,
  );
  if (buildTypesStart === -1 || packagingOptionsStart === -1) {
    throw new Error('withAndroidReleaseSafety could not locate Android buildTypes');
  }

  const buildTypes = next
    .slice(buildTypesStart, packagingOptionsStart)
    .replace(
      /(debug\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.[A-Za-z]+/,
      '$1signingConfig signingConfigs.debug',
    )
    .replace(
      /(release\s*\{[\s\S]*?)signingConfig\s+signingConfigs\.[A-Za-z]+/,
      '$1signingConfig signingConfigs.release',
    );

  next = `${next.slice(0, buildTypesStart)}${buildTypes}${next.slice(packagingOptionsStart)}`;

  return next;
}

function withAndroidReleaseSafety(config) {
  config = withAndroidManifest(config, (manifestConfig) => {
    const application = manifestConfig.modResults.manifest.application?.[0];
    const mainActivity = application?.activity?.find(
      (activity) => activity.$?.['android:name'] === '.MainActivity',
    );

    if (mainActivity?.$) {
      delete mainActivity.$['android:screenOrientation'];
      mainActivity.$['android:resizeableActivity'] = 'true';
    }

    return manifestConfig;
  });

  config = withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('withAndroidReleaseSafety requires a Groovy app build.gradle');
    }
    gradleConfig.modResults.contents = patchBuildGradle(
      gradleConfig.modResults.contents,
    );
    return gradleConfig;
  });

  config = withAndroidStyles(config, (stylesConfig) => {
    const appTheme = AndroidConfig.Styles.getAppThemeGroup();
    stylesConfig.modResults = AndroidConfig.Styles.removeStylesItem({
      name: 'android:statusBarColor',
      parent: appTheme,
      xml: stylesConfig.modResults,
    });
    stylesConfig.modResults = AndroidConfig.Styles.removeStylesItem({
      name: 'android:navigationBarColor',
      parent: appTheme,
      xml: stylesConfig.modResults,
    });
    return stylesConfig;
  });

  return config;
}

module.exports = withAndroidReleaseSafety;
