import { Platform, StyleSheet } from 'react-native'
import {
  CONTROL_RADIUS,
  PILL_RADIUS,
  type FiltersPanelStyleContext,
} from './context'

export const getLightRouteStyles = ({ colors, isMobile }: FiltersPanelStyleContext) =>
  ({
    lightStepBlock: {
      paddingVertical: isMobile ? 12 : 14,
      paddingHorizontal: 0,
      gap: isMobile ? 8 : 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.borderLight,
    },
    lightStepHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 2,
    },
    lightStepNumber: {
      width: 22,
      height: 22,
      borderRadius: PILL_RADIUS,
      backgroundColor: colors.primary,
      color: colors.textOnPrimary,
      fontSize: 11,
      fontWeight: '700',
      textAlign: 'center',
      lineHeight: 22,
      overflow: 'hidden',
    },
    lightStepTitle: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      letterSpacing: 0,
    },
    lightStepBadge: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.primary,
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: PILL_RADIUS,
      overflow: 'hidden',
      letterSpacing: 0,
    },
    lightStepHint: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textMuted,
      lineHeight: 17,
    },
    lightCheckBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: colors.successLight,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: CONTROL_RADIUS,
    },
    lightCheckText: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.success,
    },
    lightSectionLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
      marginBottom: 6,
    },
    lightPointsList: {
      gap: 6,
    },
    lightPointRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 6,
      paddingHorizontal: 4,
      borderRadius: CONTROL_RADIUS,
      backgroundColor: colors.backgroundSecondary,
    },
    lightPointDot: {
      width: 22,
      height: 22,
      borderRadius: PILL_RADIUS,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    lightPointDotText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textOnPrimary,
    },
    lightPointLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: '500',
      color: colors.text,
    },
    lightPointRemove: {
      width: 32,
      height: 32,
      borderRadius: PILL_RADIUS,
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
      marginHorizontal: 0,
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
      ...(Platform.OS === 'web' ? ({ boxShadow: 'none' } as any) : null),
    },
    lightPointRemoveDisabled: {
      opacity: 0.3,
    },
  }) as const
