import { Platform, StyleSheet } from 'react-native'

import { DESIGN_TOKENS } from '@/constants/designSystem'
import type { ThemedColors } from '@/hooks/useTheme'

export const createCommentsSectionStyles = (colors: ThemedColors) =>
  StyleSheet.create<Record<string, any>>({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
      padding: Platform.select({ default: DESIGN_TOKENS.spacing.md, web: DESIGN_TOKENS.spacing.lg }),
      borderRadius: DESIGN_TOKENS.radii.md,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: DESIGN_TOKENS.spacing.xl },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: DESIGN_TOKENS.spacing.sm,
      marginBottom: DESIGN_TOKENS.spacing.lg,
      paddingBottom: DESIGN_TOKENS.spacing.md,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    title: {
      fontSize: Platform.select({ default: 20, web: 22 }),
      fontWeight: DESIGN_TOKENS.typography.weights.semibold,
      color: colors.text,
      letterSpacing: -0.3,
    },
    loginPrompt: {
      backgroundColor: colors.primarySoft,
      borderRadius: DESIGN_TOKENS.radii.md,
      padding: DESIGN_TOKENS.spacing.md,
      marginBottom: DESIGN_TOKENS.spacing.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.primaryAlpha30,
      ...Platform.select({ web: { cursor: 'pointer', transition: 'all 0.2s ease' } as any }),
    },
    loginPromptRow: { flexDirection: 'row', alignItems: 'center', gap: DESIGN_TOKENS.spacing.sm },
    loginText: {
      fontSize: DESIGN_TOKENS.typography.sizes.md - 1,
      color: colors.primaryText,
      fontWeight: DESIGN_TOKENS.typography.weights.medium,
    },
    loadPrompt: {
      gap: DESIGN_TOKENS.spacing.sm,
      padding: DESIGN_TOKENS.spacing.md,
      marginBottom: DESIGN_TOKENS.spacing.md,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    loadPromptText: {
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      color: colors.textMuted,
      lineHeight: 20,
    },
    loadPromptButton: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: DESIGN_TOKENS.spacing.xs,
      paddingVertical: DESIGN_TOKENS.spacing.sm,
      paddingHorizontal: DESIGN_TOKENS.spacing.md,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.primary,
    },
    loadPromptButtonText: {
      color: colors.primaryText,
      fontWeight: DESIGN_TOKENS.typography.weights.semibold,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
    },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: DESIGN_TOKENS.spacing.sm,
      marginBottom: DESIGN_TOKENS.spacing.md,
      padding: DESIGN_TOKENS.spacing.md,
      borderRadius: DESIGN_TOKENS.radii.md,
      borderWidth: 1,
      borderColor: colors.warning,
      backgroundColor: colors.warningSoft,
    },
    errorBannerText: {
      flex: 1,
      minWidth: 180,
      color: colors.text,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      lineHeight: 20,
    },
    errorBannerButton: {
      paddingHorizontal: DESIGN_TOKENS.spacing.md,
      paddingVertical: DESIGN_TOKENS.spacing.sm,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.surface,
    },
    errorBannerButtonText: {
      color: colors.warning,
      fontWeight: DESIGN_TOKENS.typography.weights.semibold,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
    },
    threadControls: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: DESIGN_TOKENS.spacing.sm,
      marginBottom: DESIGN_TOKENS.spacing.md,
    },
    threadControlButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: DESIGN_TOKENS.spacing.xs,
      paddingHorizontal: DESIGN_TOKENS.spacing.md,
      paddingVertical: DESIGN_TOKENS.spacing.sm,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    threadControlText: {
      color: colors.primary,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      fontWeight: DESIGN_TOKENS.typography.weights.medium,
    },
    commentsList: {
      gap: DESIGN_TOKENS.spacing.md,
    },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: DESIGN_TOKENS.spacing.xxl,
      gap: DESIGN_TOKENS.spacing.sm,
    },
    emptyText: {
      color: colors.text,
      fontSize: DESIGN_TOKENS.typography.sizes.lg,
      fontWeight: DESIGN_TOKENS.typography.weights.semibold,
      textAlign: 'center',
    },
    emptySubtext: {
      color: colors.textMuted,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      textAlign: 'center',
      maxWidth: 360,
      lineHeight: 20,
    },
    commentThread: {
      gap: DESIGN_TOKENS.spacing.sm,
    },
    toggleThreadButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: DESIGN_TOKENS.spacing.xs,
      paddingLeft: DESIGN_TOKENS.spacing.lg,
    },
    threadLine: {
      width: 16,
      height: 1,
      backgroundColor: colors.border,
    },
    toggleThreadText: {
      color: colors.primary,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      fontWeight: DESIGN_TOKENS.typography.weights.medium,
    },
    repliesContainer: {
      gap: DESIGN_TOKENS.spacing.sm,
      paddingLeft: DESIGN_TOKENS.spacing.lg,
      borderLeftWidth: 1,
      borderLeftColor: colors.borderLight,
      marginLeft: DESIGN_TOKENS.spacing.sm,
    },
    nestedRepliesContainer: {
      gap: DESIGN_TOKENS.spacing.sm,
      paddingLeft: DESIGN_TOKENS.spacing.md,
    },
    parentChainContainer: {
      gap: DESIGN_TOKENS.spacing.sm,
      padding: DESIGN_TOKENS.spacing.sm,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.surfaceMuted,
      borderWidth: 1,
      borderColor: colors.borderLight,
      marginBottom: DESIGN_TOKENS.spacing.xs,
    },
    parentChainHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: DESIGN_TOKENS.spacing.xs,
    },
    parentChainLabel: {
      color: colors.textMuted,
      fontSize: DESIGN_TOKENS.typography.sizes.sm,
      flex: 1,
    },
  })
