// components/travel/travelWizardHeaderStyles.ts
// E10: Styles extracted from TravelWizardHeader.tsx (~410 LOC)

import { StyleSheet, Platform } from 'react-native';
import { DESIGN_TOKENS } from '@/constants/designSystem';
import type { useThemedColors } from '@/hooks/useTheme';

export const createWizardHeaderStyles = (colors: ReturnType<typeof useThemedColors>) => StyleSheet.create({
    headerWrapper: {
        paddingHorizontal: DESIGN_TOKENS.spacing.md,
        paddingTop: DESIGN_TOKENS.spacing.sm,
        paddingBottom: DESIGN_TOKENS.spacing.sm,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    headerWrapperMobile: {
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
        paddingTop: DESIGN_TOKENS.spacing.xs,
        paddingBottom: DESIGN_TOKENS.spacing.xs,
    },
    topNavRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: DESIGN_TOKENS.spacing.sm,
    },
    leftNav: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.sm,
        flex: 1,
        minWidth: 0,
    },
    rightNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        flexShrink: 0,
    },
    rightActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        flexShrink: 0,
    },
    // --- Компактная мобильная шапка (3 ряда) ---
    mobileTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
    },
    headerTitleMobileInline: {
        flex: 1,
        minWidth: 0,
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
    },
    mobileMetaActionRow: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: DESIGN_TOKENS.spacing.sm,
    },
    mobileMetaLeft: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        flexWrap: 'wrap',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: DESIGN_TOKENS.spacing.sm,
        marginTop: DESIGN_TOKENS.spacing.xs,
    },
    titleRowMobile: {
        // Заголовок слева (flex:1), меню «…» справа на той же строке —
        // не отдельной висящей строкой (см. QA F-15 «одинокий элемент …»).
        alignItems: 'flex-start',
    },
    titleActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        flexShrink: 0,
    },
    titleActionsRowMobile: {
        flexWrap: 'wrap',
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.sm,
    },
    headerRowMobile: {
        flexDirection: 'column',
        alignItems: 'stretch',
        gap: DESIGN_TOKENS.spacing.xs,
    },
    headerRightRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
    },
    iconButton: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 44,
        height: 44,
        minWidth: 44,
        minHeight: 44,
        borderRadius: DESIGN_TOKENS.radii.pill,
        position: 'relative',
        backgroundColor: colors.surfaceMuted,
        borderWidth: 0,
    },
    iconButtonMobile: {
        width: 44,
        height: 44,
        minWidth: 44,
        minHeight: 44,
    },
    iconButtonActive: {
        backgroundColor: colors.primarySoft,
        borderWidth: 0,
    },
    menuPanel: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        borderRadius: DESIGN_TOKENS.radii.md,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
        ...(Platform.OS === 'web'
            ? ({ boxShadow: DESIGN_TOKENS.shadows.card } as any)
            : (DESIGN_TOKENS.shadowsNative.light as any)),
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.sm,
        paddingHorizontal: DESIGN_TOKENS.spacing.md,
        minHeight: 44,
    },
    menuItemText: {
        flex: 1,
        fontSize: 14,
        fontWeight: '600',
        color: colors.text,
    },
    actionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
        minHeight: 44,
        borderRadius: DESIGN_TOKENS.radii.pill,
        borderWidth: 1,
    },
    actionButtonMobile: {
        minHeight: 44,
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
    },
    actionButtonSecondary: {
        backgroundColor: colors.surfaceMuted,
        borderColor: colors.border,
    },
    actionButtonSaving: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primaryAlpha40,
    },
    actionButtonPrimary: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    actionButtonDisabled: {
        opacity: 0.6,
    },
    actionButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text,
    },
    actionButtonPrimaryText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textOnPrimary,
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        height: 34,
        minHeight: 44,
        paddingHorizontal: 10,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
    },
    backButtonMobile: {
        minHeight: 44,
        paddingHorizontal: 10,
    },
    backButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text,
    },
    titleColumn: {
        flex: 1,
        minWidth: 0,
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 2,
    },
    headerTitleMobile: {
        fontSize: 16,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 2,
    },
    headerSubtitle: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '500',
    },
    headerSubtitleMobile: {
        fontSize: 12,
        color: colors.textMuted,
    },
    titleBlock: {
        marginTop: DESIGN_TOKENS.spacing.xs,
    },
    autosaveBadge: {
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
        paddingVertical: DESIGN_TOKENS.spacing.xxs,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.primarySoft,
    },
    previewButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        paddingVertical: DESIGN_TOKENS.spacing.xs,
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.primarySoft,
        borderWidth: 1,
        borderColor: colors.primaryAlpha40,
        minHeight: 32,
    },
    previewButtonText: {
        fontSize: DESIGN_TOKENS.typography.sizes.xs,
        fontWeight: '700',
        color: colors.primaryText,
    },
    mobileMetaRow: {
        marginTop: 0,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
    },
    autosaveBadgeText: {
        fontSize: 11,
        color: colors.primaryText,
        fontWeight: '600',
    },
    tipToggleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        height: 32,
        minHeight: 44,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
    },
    tipToggleButtonActive: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primary,
    },
    tipToggleText: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.textMuted,
    },
    tipToggleTextActive: {
        color: colors.primaryText,
    },
    progressBarTrack: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        width: '100%',
        height: 6,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.border,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        borderRadius: DESIGN_TOKENS.radii.pill,
    },
    progressMetaRow: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        minHeight: 18,
    },
    progressMetaRowInline: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: DESIGN_TOKENS.spacing.sm,
    },
    progressMetaText: {
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '500',
    },
    stepSelectTrigger: {
        minHeight: 28,
        maxWidth: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: DESIGN_TOKENS.spacing.xs,
        paddingVertical: DESIGN_TOKENS.spacing.xxs,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
    },
    stepSelectTriggerActive: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primaryAlpha40,
    },
    stepSelectTriggerText: {
        minWidth: 0,
        flexShrink: 1,
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '700',
    },
    stepSelectPanel: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        borderRadius: DESIGN_TOKENS.radii.md,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: colors.border,
        overflow: 'hidden',
        ...(Platform.OS === 'web'
            ? ({ boxShadow: DESIGN_TOKENS.shadows.card } as any)
            : (DESIGN_TOKENS.shadowsNative.light as any)),
    },
    stepSelectItem: {
        minHeight: 48,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.sm,
        paddingHorizontal: DESIGN_TOKENS.spacing.sm,
        paddingVertical: DESIGN_TOKENS.spacing.xs,
    },
    stepSelectItemActive: {
        backgroundColor: colors.primarySoft,
    },
    stepSelectBadge: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
    },
    stepSelectBadgeActive: {
        backgroundColor: colors.primarySoft,
        borderColor: colors.primaryAlpha40,
    },
    stepSelectBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textMuted,
    },
    stepSelectItemTextGroup: {
        flex: 1,
        minWidth: 0,
    },
    stepSelectItemTitle: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.text,
    },
    stepSelectItemTitleActive: {
        color: colors.primaryText,
    },
    stepSelectItemSubtitle: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: '500',
        color: colors.textMuted,
    },
    progressStatusGroup: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        flexWrap: 'wrap',
    },
    progressErrorBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: DESIGN_TOKENS.spacing.xs,
        minHeight: 20,
        borderRadius: DESIGN_TOKENS.radii.pill,
        backgroundColor: colors.dangerSoft,
    },
    progressErrorText: {
        fontSize: 11,
        color: colors.dangerDark,
        fontWeight: '700',
    },
    belowProgressRow: {
        marginTop: DESIGN_TOKENS.spacing.xs,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: DESIGN_TOKENS.spacing.md,
    },
    belowProgressLeft: {
        flex: 1,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.sm,
    },
    belowProgressRight: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        flexShrink: 0,
    },
    webActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        gap: DESIGN_TOKENS.spacing.xs,
        flexWrap: 'nowrap',
    },
    milestonesInlineWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESIGN_TOKENS.spacing.xs,
        flexWrap: 'nowrap',
    },
    tipPanel: {
        marginTop: DESIGN_TOKENS.spacing.sm,
        padding: DESIGN_TOKENS.spacing.sm,
        borderRadius: DESIGN_TOKENS.radii.md,
        backgroundColor: colors.surfaceMuted,
        borderWidth: 1,
        borderColor: colors.border,
    },
    tipPanelTitle: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text,
        marginBottom: 4,
    },
    tipPanelBody: {
        fontSize: 12,
        color: colors.textMuted,
        lineHeight: 16,
    },
    milestonesWrapper: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: DESIGN_TOKENS.spacing.sm,
        marginBottom: DESIGN_TOKENS.spacing.xs,
        paddingHorizontal: 4,
    },
    milestoneInline: {
        alignItems: 'center',
        justifyContent: 'center',
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.surface,
    },
    milestoneInlineActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    milestoneInlineNumber: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.textMuted,
    },
    milestoneInlineNumberActive: {
        color: colors.primaryText,
    },
    milestone: {
        alignItems: 'center',
        justifyContent: 'center',
        minWidth: 28,
        minHeight: 28,
    },
    milestoneActive: {},
    milestoneCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: colors.border,
        backgroundColor: colors.surface,
        alignItems: 'center',
        justifyContent: 'center',
    },
    milestoneCircleActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primarySoft,
    },
    milestoneNumber: {
        fontSize: 11,
        fontWeight: '700',
        color: colors.textMuted,
    },
    milestoneNumberActive: {
        color: colors.primaryText,
    },
});
