import { Dimensions, Platform, StyleSheet } from 'react-native';
import { DESIGN_TOKENS } from '@/constants/designSystem';
import { LAYOUT } from '@/constants/layout';
import type { ThemedColors } from '@/hooks/useTheme';

export const getFiltersPanelStyles = (colors: ThemedColors, isMobile: boolean, windowWidth: number) => {
  const panelWidth = isMobile ? '100%' : Math.max(Math.min(windowWidth - 24, 480), 280);
  const windowHeight = Dimensions.get('window').height;
  const bottomDockReserve = Platform.OS === 'web' && isMobile ? LAYOUT.tabBarHeight : 0;

  return StyleSheet.create({
    card: {
      backgroundColor: colors.surface,
      borderRadius: isMobile ? 0 : 14,
      padding: isMobile ? 0 : 12,
      width: panelWidth,
      maxWidth: '100%',
      height: '100%',
      maxHeight: windowHeight,
      display: 'flex',
      flexDirection: 'column',
      ...(isMobile
        ? {}
        : {
            shadowColor: (colors.shadows as any)?.shadowColor ?? DESIGN_TOKENS.shadowsNative.light.shadowColor,
            shadowOffset: { width: 0, height: 6 },
            shadowOpacity: 0.07,
            shadowRadius: 12,
            elevation: 6,
          }),
      alignSelf: isMobile ? 'stretch' : 'flex-start',
    },
    headerContainer: {
      marginBottom: 12,
    },
    stickyTop: {
      gap: 8,
      ...(Platform.OS === 'web'
        ? ({
            position: 'sticky',
            top: 0,
            zIndex: 5,
            backgroundColor: colors.surface,
            paddingTop: 4,
          } as any)
        : null),
    },
    compactHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    compactTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    compactTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.text,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.text,
    },
    counterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 8,
    },
    counterBadge: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
    },
    counterLabel: {
      fontSize: 13,
      color: colors.textMuted,
      fontWeight: '600',
    },
    counterHint: {
      fontSize: 12,
      color: colors.textMuted,
      fontWeight: '600',
    },
    counterValue: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.primary,
    },
    modeHelper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 4,
      paddingVertical: 6,
    },
    modeHelperText: {
      fontSize: 12,
      color: colors.textMuted,
      flex: 1,
    },
    content: {
      flex: 1,
      flexGrow: 1,
    },
    contentContainer: {
      paddingBottom: 100 + bottomDockReserve,
      flexGrow: 1,
    },
    section: {
      marginBottom: 12,
    },
    sectionCard: {
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      gap: 10,
      ...DESIGN_TOKENS.shadowsNative.light,
    },
    dualInputRow: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'stretch',
    },
    separator: {
      width: 1,
      backgroundColor: colors.border,
    },
    transportSection: {
      gap: 8,
    },
    routePointsList: {
      marginTop: 10,
      gap: 10,
    },
    routePointRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    routePointPill: {
      flex: 1,
      minWidth: 0,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 999,
      backgroundColor: colors.overlay,
    },
    routePointPillText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textOnDark,
    },
    routePointRemoveBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.overlay,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
      marginHorizontal: 0,
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
      ...(Platform.OS === 'web' ? ({ boxShadow: 'none' } as any) : null),
    },
    routePointRemoveBtnDisabled: {
      opacity: 0.4,
    },
    sectionTight: {
      marginBottom: 8,
    },
    sectionLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    sectionHint: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 6,
    },
    input: {
      height: 40,
      borderRadius: 10,
      paddingHorizontal: 12,
      fontSize: 14,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      ...DESIGN_TOKENS.shadowsNative.light,
    },
    chipsContainer: {
      marginTop: 8,
    },
    chipsContent: {
      alignItems: 'center',
      paddingRight: 2,
    },
    categoryChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 14,
      maxWidth: 112,
      marginRight: 6,
    },
    categoryChipText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
      flexShrink: 1,
      marginRight: 4,
    },
    categoryChipIconButton: {
      width: 24,
      height: 24,
      borderRadius: 12,
      marginHorizontal: 0,
      backgroundColor: 'transparent',
      shadowColor: 'transparent',
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
      ...(Platform.OS === 'web' ? ({ boxShadow: 'none' } as any) : null),
    },
    moreChip: {
      backgroundColor: colors.primarySoft,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 14,
    },
    moreChipText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },
    radiusQuickOptions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 8,
    },
    transportTabs: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 10,
      padding: 2,
    },
    transportTabsDisabled: {
      opacity: 0.5,
    },
    routeInfo: {
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderRadius: 10,
      padding: 12,
      ...DESIGN_TOKENS.shadowsNative.light,
    },
    routeInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 8,
    },
    routePill: {
      flex: 1,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    routePillLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textMuted,
      marginBottom: 4,
    },
    routePillValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    routePillDivider: {
      width: 1,
      alignSelf: 'stretch',
      backgroundColor: colors.border,
    },
    routeDistanceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: 4,
    },
    routeItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 4,
    },
    routeLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textMuted,
      flex: 1,
    },
    routeValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
      flex: 2,
      textAlign: 'right',
      marginLeft: 8,
    },
    routeDistance: {
      fontSize: 13,
      fontWeight: '800',
      color: colors.primary,
    },
    compactButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: DESIGN_TOKENS.radii.sm,
      minHeight: 40,
      marginLeft: 8,
    },
    compactButtonSmall: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      minHeight: 36,
    },
    compactButtonText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textOnPrimary,
      marginLeft: 6,
    },
    footer: {
      marginTop: 8,
      paddingTop: 8,
    },
    infoBox: {
      backgroundColor: colors.primarySoft,
      borderRadius: 10,
      padding: 12,
      marginBottom: 12,
    },
    infoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 6,
    },
    infoText: {
      fontSize: 13,
      color: colors.text,
      fontWeight: '700',
    },
    infoTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    infoItem: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 2,
    },
    infoBold: {
      fontWeight: '700',
      color: colors.primary,
    },
    routeHintContainer: {
      marginTop: 12,
      marginBottom: 12,
    },
    routeStatsContainer: {
      marginTop: 12,
      marginBottom: 12,
    },
    stepper: {
      marginTop: 4,
      marginBottom: 12,
      gap: 8,
    },
    stepItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 10,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.border,
    },
    stepItemDone: {
      borderColor: colors.primary,
      backgroundColor: colors.primarySoft,
    },
    stepBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepBadgeStart: {
      backgroundColor: colors.success,
    },
    stepBadgeEnd: {
      backgroundColor: colors.danger,
    },
    stepBadgeTransport: {
      backgroundColor: colors.primary,
    },
    stepBadgeText: {
      color: colors.textOnPrimary,
      fontWeight: '800',
      fontSize: 12,
    },
    stepContent: {
      flex: 1,
      gap: 2,
    },
    stepTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    stepSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
    },
    routeBuilt: {
      marginTop: 6,
      padding: 12,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    routeBuiltTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.primary,
      marginBottom: 4,
    },
    routeBuiltMeta: {
      fontSize: 13,
      color: colors.text,
      fontWeight: '600',
    },
    noPointsToast: {
      marginTop: 12,
      padding: 12,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 8,
    },
    noPointsTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    noPointsSubtitle: {
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 18,
    },
    noPointsActions: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 4,
    },
    stepBlock: {
      padding: 12,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 12,
      gap: 8,
    },
    stepHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    stepBlockTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.text,
    },
    stepInlineHint: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '700',
    },
    addressToggle: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: DESIGN_TOKENS.radii.sm,
      backgroundColor: colors.primarySoft,
      borderWidth: 1,
      borderColor: colors.primary,
      marginTop: 4,
    },
    addressToggleText: {
      color: colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    sectionDisabled: {
      opacity: 0.6,
    },
    actionRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 12,
      justifyContent: 'flex-start',
      flexWrap: 'wrap',
    },
    actionGhost: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: DESIGN_TOKENS.radii.sm,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      minHeight: 40,
    },
    actionGhostText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.text,
    },
    statusCard: {
      backgroundColor: colors.mutedBackground ?? colors.backgroundSecondary,
      borderRadius: 10,
      padding: 10,
      ...DESIGN_TOKENS.shadowsNative.light,
    },
    swapButton: {
      marginTop: 10,
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.primarySoft,
    },
    swapButtonText: {
      color: colors.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    accordionHeader: {
      marginTop: 4,
      marginBottom: 6,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    accordionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.text,
    },
    mapControlsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    mapLayersSection: {
      marginTop: 12,
    },
    mapLayersRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    stickyFooter: {
      ...(Platform.OS === 'web'
        ? ({
            position: 'sticky',
            bottom: bottomDockReserve,
            backgroundColor: colors.surface,
            paddingTop: 8,
            paddingBottom: 4,
          } as any)
        : {
            paddingTop: 8,
          }),
    },
    footerButtons: {
      flexDirection: 'row',
      gap: 8,
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    ctaButton: {
      borderRadius: DESIGN_TOKENS.radii.md,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      flex: Platform.OS === 'web' ? undefined : 1,
    },
    helperText: {
      fontSize: 12,
      color: colors.textMuted,
      marginBottom: 6,
    },
  });
};
