// components/map/markersListStyles.ts
// Extracted from MarkersListComponent.tsx (C3.1)
import { useMemo } from 'react';
import type { useThemedColors } from '@/hooks/useTheme';

export const useStyles = (colors: ReturnType<typeof useThemedColors>) => useMemo(() => ({
    container: {
        position: 'relative' as const,
        // Панель — RN-Web View, её дети не растягиваются сами: без width/box-sizing
        // список ужимался по контенту, и на узкой мобильной панели адрес точки
        // оставался в колонке ~46px (обрезка «Elektroc Szo…»).
        width: '100%',
        boxSizing: 'border-box' as const,
        backgroundColor: 'transparent',
        padding: '0',
        borderRadius: '14px',
        transition: 'box-shadow 0.15s ease',
    },
    containerDragActive: {
        boxShadow: `0 0 0 2px ${colors.borderAccent}`,
    },
    dropOverlay: {
        position: 'absolute' as const,
        inset: 0,
        zIndex: 5,
        borderRadius: '14px',
        border: `2px dashed ${colors.borderAccent}`,
        backgroundColor: colors.primarySoft,
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        textAlign: 'center' as const,
        pointerEvents: 'none' as const,
    },
    dropOverlayText: {
        fontSize: '13px',
        fontWeight: 700,
        color: colors.primaryDark,
    },
    dropHint: {
        marginTop: '8px',
        fontSize: '12px',
        color: colors.textMuted,
        textAlign: 'center' as const,
    },
    dropZone: {
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        justifyContent: 'center',
        gap: '8px',
        textAlign: 'center' as const,
        padding: '24px 16px',
        borderRadius: '14px',
        border: `2px dashed ${colors.border}`,
        backgroundColor: colors.surface,
        cursor: 'pointer',
        transition: 'border-color 0.15s ease, background-color 0.15s ease',
    },
    dropZoneActive: {
        border: `2px dashed ${colors.borderAccent}`,
        backgroundColor: colors.primarySoft,
    },
    dropZoneIcon: {
        width: '44px',
        height: '44px',
        borderRadius: '999px',
        backgroundColor: colors.primarySoft,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    dropZoneTitle: {
        fontSize: '13px',
        fontWeight: 700,
        color: colors.text,
    },
    dropZoneHint: {
        fontSize: '12px',
        color: colors.textMuted,
        lineHeight: 1.4,
        maxWidth: '260px',
    },
    dropZoneCompact: {
        flexDirection: 'row' as const,
        alignItems: 'center',
        justifyContent: 'flex-start',
        textAlign: 'left' as const,
        padding: '8px 12px',
        marginBottom: '4px',
        gap: '10px',
        border: `1px dashed ${colors.border}`,
    },
    dropZoneCompactIcon: {
        width: '28px',
        height: '28px',
        borderRadius: '999px',
        backgroundColor: colors.primarySoft,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    dropZoneCompactText: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '2px',
        minWidth: 0,
    },
    stickyHeader: {
        position: 'sticky' as const,
        top: 0,
        zIndex: 3,
        backgroundColor: colors.backgroundSecondary,
        paddingBottom: '8px',
    },
    headerRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '10px',
    },
    headerRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    headerTitle: {
        fontSize: '14px',
        fontWeight: 700,
        letterSpacing: '0.2px',
        color: colors.text,
    },
    headerBadge: {
        fontSize: '12px',
        fontWeight: 700,
        padding: '2px 10px',
        borderRadius: '999px',
        backgroundColor: colors.primarySoft,
        color: colors.primaryDark,
    },
    addFromPhotoButton: {
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        color: colors.text,
        padding: '6px 10px',
        borderRadius: '10px',
        cursor: 'pointer',
        fontSize: '11px',
        whiteSpace: 'nowrap' as const,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: 600,
        transition: 'all 0.15s ease',
    },
    fileInputHidden: {
        display: 'none',
    },
    searchRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '10px 12px',
        borderRadius: '10px',
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        marginBottom: '12px',
    },
    searchInput: {
        width: '100%',
        border: 'none',
        outlineWidth: 0,
        outlineStyle: 'none' as const,
        outlineColor: 'transparent',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: 'transparent',
    },
    emptyText: {
        textAlign: 'center' as const,
        color: colors.textMuted,
        fontSize: '13px',
        lineHeight: 1.4,
    },
    emptySearchState: {
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        gap: '8px',
        padding: '18px 14px',
        borderRadius: '12px',
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        textAlign: 'center' as const,
    },
    emptySearchTitle: {
        fontSize: '13px',
        fontWeight: 700,
        color: colors.text,
    },
    emptySearchText: {
        fontSize: '12px',
        color: colors.textMuted,
        lineHeight: 1.4,
    },
    clearSearchButton: {
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.primarySoft,
        color: colors.primaryDark,
        padding: '6px 12px',
        borderRadius: '10px',
        cursor: 'pointer',
        fontSize: '12px',
        fontWeight: 700,
    },
    list: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '6px',
        width: '100%',
    },
    // Одна компактная строка вместо блока «текст сверху — кнопки снизу»: в панели
    // 380-420px прежняя карточка занимала ~170px, и на экран влезало три точки,
    // а чипы категорий с большими кнопками читались как нагромождение.
    markerItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        border: `1px solid ${colors.border}`,
        borderRadius: '12px',
        padding: '6px 4px 6px 6px',
        width: '100%',
        boxSizing: 'border-box' as const,
        backgroundColor: colors.surface,
        cursor: 'pointer',
        transition: 'border-color 0.15s ease, background-color 0.15s ease, opacity 0.15s ease',
    },
    // Узкая панель (мобильный bottom-sheet ~250px контента): в одну строку
    // текст точки сжимался до ~50px, поэтому действия уезжают под адрес,
    // а тач-таргеты остаются полноразмерными.
    markerItemCompact: {
        flexDirection: 'column' as const,
        alignItems: 'stretch' as const,
        gap: '4px',
        padding: '8px',
    },
    compactMain: {
        display: 'flex',
        alignItems: 'center',
        gap: '10px',
        minWidth: 0,
    },
    compactToolbar: {
        display: 'flex',
        alignItems: 'center',
        gap: '2px',
    },
    compactToolbarSpacer: {
        flex: 1,
    },
    markerItemDragging: {
        opacity: 0.4,
    },
    markerItemDragOver: {
        border: `1px solid ${colors.borderAccent}`,
        boxShadow: `0 0 0 2px ${colors.primarySoft}`,
    },
    // #1040 — колонка ↑/↓ слева. HTML5 drag не работает по тачу (mobile web),
    // поэтому кнопки — единственный способ поменять порядок точек на телефоне;
    // на десктопе они дублируют drag за ту же ручку и никому не мешают.
    reorderColumn: {
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
        width: '26px',
        cursor: 'grab',
        touchAction: 'none' as const,
    },
    reorderButton: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '26px',
        height: '24px',
        padding: 0,
        border: 'none',
        borderRadius: '6px',
        backgroundColor: 'transparent',
        color: colors.textMuted,
        cursor: 'pointer',
        transition: 'background-color 0.15s ease',
    },
    reorderButtonHover: {
        backgroundColor: colors.surfaceMuted,
    },
    reorderButtonDisabled: {
        opacity: 0.25,
        cursor: 'default',
    },
    editingItem: {
        border: `1px solid ${colors.borderAccent}`,
        backgroundColor: colors.primarySoft,
    },
    activeItem: {
        border: `1px solid ${colors.borderAccent}`,
        backgroundColor: colors.surfaceElevated,
    },
    thumbnailWrapper: {
        position: 'relative' as const,
        width: '48px',
        height: '48px',
        borderRadius: '10px',
        backgroundColor: colors.surfaceMuted,
        border: `1px solid ${colors.borderLight}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        flexShrink: 0,
    },
    previewMedia: {
        width: '100%',
        height: '100%',
    },
    placeholderImage: {
        width: '100%',
        height: '100%',
        backgroundColor: colors.surfaceMuted,
    },
    // Номер точки лежит НА миниатюре: отдельный кружок в строке съедал 34px
    // ширины, из-за чего длинный адрес рвался на три строки.
    indexBadge: {
        position: 'absolute' as const,
        top: '3px',
        left: '3px',
        minWidth: '16px',
        height: '16px',
        padding: '0 4px',
        borderRadius: '999px',
        // Не overlay: в светлой теме это 40% чёрного, и белая цифра на нём тонет.
        // Плашка цвета поверхности читается и на фото, и на пустом плейсхолдере.
        backgroundColor: colors.surface,
        color: colors.text,
        border: `1px solid ${colors.border}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '10px',
        fontWeight: 700,
        boxSizing: 'border-box' as const,
    },
    previewText: {
        flex: 1,
        minWidth: 0,
    },
    markerTitle: {
        fontSize: '13px',
        fontWeight: 600,
        color: colors.text,
        lineHeight: 1.3,
        display: '-webkit-box',
        WebkitLineClamp: 2,
        WebkitBoxOrient: 'vertical' as const,
        overflow: 'hidden',
    },
    // Мета — одна тихая строка вместо двух цветных чипов.
    metaRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '5px',
        marginTop: '3px',
        minWidth: 0,
    },
    metaText: {
        fontSize: '11px',
        color: colors.textMuted,
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden' as const,
        textOverflow: 'ellipsis' as const,
    },
    metaSeparator: {
        fontSize: '11px',
        color: colors.textSubtle,
        flexShrink: 0,
    },
    actions: {
        display: 'flex',
        flexDirection: 'row' as const,
        alignItems: 'center',
        flexShrink: 0,
    },
    // Тач-таргет 44px держит сама кнопка (прозрачная рамка), видимая подложка
    // появляется только на hover — иконки не спорят с названием точки.
    iconAction: {
        width: '44px',
        height: '44px',
        padding: 0,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        border: 'none',
        borderRadius: '10px',
        backgroundColor: 'transparent',
        cursor: 'pointer',
        transition: 'background-color 0.15s ease',
    },
    iconActionHover: {
        backgroundColor: colors.surfaceMuted,
    },
    iconActionDangerHover: {
        backgroundColor: colors.dangerSoft,
    },

    editForm: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '12px',
    },
    editHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '4px',
    },
    editTitle: {
        fontSize: '14px',
        fontWeight: 600,
        color: colors.text,
    },
    editSubtitle: {
        fontSize: '12px',
        color: colors.textMuted,
        marginTop: '2px',
        maxWidth: '260px',
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    closeIconButton: {
        border: 'none',
        backgroundColor: 'transparent',
        fontSize: '16px',
        lineHeight: 1,
        cursor: 'pointer',
        color: colors.textMuted,
        padding: '2px 6px',
        borderRadius: '999px',
    },
    helperText: {
        fontSize: '12px',
        color: colors.textMuted,
        lineHeight: 1.4,
    },
    field: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '4px',
        fontSize: '12px',
    },
    fieldLabel: {
        fontWeight: 500,
        color: colors.text,
    },
    fieldHint: {
        fontSize: '11px',
        color: colors.textMuted,
        lineHeight: 1.4,
    },
    input: {
        width: '100%',
        padding: '8px',
        border: `1px solid ${colors.border}`,
        borderRadius: '6px',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: colors.surface,
    },
    imagePreview: {
        width: '100px',
        height: '100px',
        objectFit: 'contain' as const,
        borderRadius: '6px',
        backgroundColor: colors.backgroundSecondary,
        marginTop: '4px',
    },
    actionsRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
        marginTop: '4px',
        flexWrap: 'wrap' as const,
    },
    primaryActions: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap' as const,
    },
    primaryButton: {
        backgroundColor: colors.primary,
        color: colors.textInverse,
        border: 'none',
        padding: '6px 14px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 500,
    },
    secondaryButton: {
        backgroundColor: colors.surface,
        color: colors.text,
        border: `1px solid ${colors.border}`,
        padding: '6px 12px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: '13px',
    },
    deleteTextButton: {
        backgroundColor: 'transparent',
        color: colors.danger,
        border: 'none',
        padding: '4px 0',
        cursor: 'pointer',
        fontSize: '12px',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        whiteSpace: 'nowrap' as const,
    },
    modalOverlay: {
        position: 'fixed' as const,
        inset: 0,
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBackdrop: {
        position: 'absolute' as const,
        inset: 0,
        backgroundColor: colors.overlay,
    },
    modalContent: {
        position: 'relative' as const,
        backgroundColor: colors.surface,
        borderRadius: '12px',
        maxWidth: '720px',
        width: '90%',
        maxHeight: '90vh',
        padding: '20px 24px',
        boxShadow: colors.boxShadows.modal,
        overflowY: 'auto' as const,
    },
    multiSelect: {
        border: `1px solid ${colors.border}`,
        borderRadius: '10px',
        padding: '8px 12px',
        backgroundColor: colors.surface,
        minHeight: '44px',
        boxShadow: colors.boxShadows.card,
    },
    multiSelectDropdownContainer: {
        borderRadius: '12px',
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        boxShadow: colors.boxShadows.card,
        padding: '6px',
    },
    multiSelectPlaceholder: {
        fontSize: '13px',
        color: colors.textMuted,
        fontWeight: 500,
    },
    multiSelectSelectedText: {
        fontSize: '13px',
        color: colors.text,
        fontWeight: 600,
    },
    multiSelectSearchInput: {
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '8px 10px',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: colors.backgroundSecondary,
    },
}), [colors]);
