// components/map/markersListStyles.ts
// Extracted from MarkersListComponent.tsx (C3.1)
import { useMemo } from 'react';
import type { useThemedColors } from '@/hooks/useTheme';

export const useStyles = (colors: ReturnType<typeof useThemedColors>) => useMemo(() => ({
    container: {
        backgroundColor: 'transparent',
        padding: '0',
    },
    headerRow: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '10px',
    },
    headerRight: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    headerTitle: {
        fontSize: '14px',
        fontWeight: 700,
        letterSpacing: '0.2px',
        color: colors.text,
    },
    headerBadge: {
        fontSize: '12px',
        fontWeight: 700,
        padding: '2px 10px',
        borderRadius: '999px',
        backgroundColor: colors.primarySoft,
        color: colors.primaryDark,
    },
    addFromPhotoButton: {
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        color: colors.text,
        padding: '6px 10px',
        borderRadius: '10px',
        cursor: 'pointer',
        fontSize: '11px',
        whiteSpace: 'nowrap' as const,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: 600,
        transition: 'all 0.15s ease',
    },
    fileInputHidden: {
        display: 'none',
    },
    searchRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '10px 12px',
        borderRadius: '10px',
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        marginBottom: '12px',
    },
    searchInput: {
        width: '100%',
        border: 'none',
        outlineWidth: 0,
        outlineStyle: 'none' as const,
        outlineColor: 'transparent',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: 'transparent',
    },
    emptyText: {
        textAlign: 'center' as const,
        color: colors.textMuted,
        fontSize: '13px',
        lineHeight: 1.4,
    },
    list: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '8px',
    },
    markerItem: {
        border: `1px solid ${colors.border}`,
        borderRadius: '12px',
        padding: '10px 12px',
        backgroundColor: colors.surface,
        boxShadow: colors.boxShadows.card,
        cursor: 'pointer',
        transition: 'border-color 0.15s ease, box-shadow 0.15s ease',
    },
    editingItem: {
        border: `1px solid ${colors.borderAccent}`,
        boxShadow: `0 0 0 3px ${colors.primarySoft}`,
    },
    activeItem: {
        border: `1px solid ${colors.borderAccent}`,
        boxShadow: `0 0 0 3px ${colors.accentSoft}`,
    },
    row: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
    },
    indexBadge: {
        width: '26px',
        height: '26px',
        borderRadius: '999px',
        backgroundColor: colors.backgroundSecondary,
        color: colors.text,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '12px',
    },
    thumbnailWrapper: {
        width: '56px',
        height: '56px',
        borderRadius: '10px',
        backgroundColor: colors.backgroundSecondary,
        border: `1px solid ${colors.border}`,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
        flexShrink: 0,
    },
    previewImage: {
        width: '100%',
        height: '100%',
        objectFit: 'cover' as const,
    },
    previewMedia: {
        width: '100%',
        height: '100%',
    },
    placeholderImage: {
        fontSize: '10px',
        color: colors.textMuted,
        textAlign: 'center' as const,
        padding: '4px',
        lineHeight: 1.2,
    },
    previewText: {
        flex: 1,
        minWidth: 0,
        marginRight: '8px',
    },
    markerTitle: {
        fontSize: '13px',
        fontWeight: 700,
        color: colors.text,
        lineHeight: 1.25,
        marginBottom: '4px',
        display: '-webkit-box',
        WebkitLineClamp: 2,
        WebkitBoxOrient: 'vertical' as const,
        overflow: 'hidden',
    },
    metaRow: {
        display: 'flex',
        flexWrap: 'wrap' as const,
        gap: '6px',
        marginTop: '4px',
    },
    badge: {
        fontSize: '11px',
        padding: '2px 6px',
        borderRadius: '999px',
        backgroundColor: colors.accentSoft,
        color: colors.accentDark,
    },
    badgeMuted: {
        fontSize: '11px',
        padding: '2px 6px',
        borderRadius: '999px',
        backgroundColor: colors.backgroundSecondary,
        color: colors.textMuted,
    },
    actions: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '6px',
        marginLeft: '8px',
        flexShrink: 0,
        alignSelf: 'flex-start',
    },
    editButton: {
        backgroundColor: colors.primarySoft,
        color: colors.text,
        border: `1px solid ${colors.border}`,
        padding: '6px 10px',
        borderRadius: '10px',
        cursor: 'pointer',
        fontSize: '11px',
        whiteSpace: 'nowrap' as const,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: 600,
    },
    deleteButton: {
        backgroundColor: colors.dangerSoft,
        color: colors.dangerDark,
        border: `1px solid ${colors.dangerLight}`,
        padding: '6px 10px',
        borderRadius: '10px',
        cursor: 'pointer',
        fontSize: '11px',
        whiteSpace: 'nowrap' as const,
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        fontWeight: 600,
    },
    editForm: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '12px',
    },
    editHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '4px',
    },
    editTitle: {
        fontSize: '14px',
        fontWeight: 600,
        color: colors.text,
    },
    editSubtitle: {
        fontSize: '12px',
        color: colors.textMuted,
        marginTop: '2px',
        maxWidth: '260px',
        whiteSpace: 'nowrap' as const,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
    },
    closeIconButton: {
        border: 'none',
        backgroundColor: 'transparent',
        fontSize: '16px',
        lineHeight: 1,
        cursor: 'pointer',
        color: colors.textMuted,
        padding: '2px 6px',
        borderRadius: '999px',
    },
    helperText: {
        fontSize: '12px',
        color: colors.textMuted,
        lineHeight: 1.4,
    },
    field: {
        display: 'flex',
        flexDirection: 'column' as const,
        gap: '4px',
        fontSize: '12px',
    },
    fieldLabel: {
        fontWeight: 500,
        color: colors.text,
    },
    fieldHint: {
        fontSize: '11px',
        color: colors.textMuted,
        lineHeight: 1.4,
    },
    input: {
        width: '100%',
        padding: '8px',
        border: `1px solid ${colors.border}`,
        borderRadius: '6px',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: colors.surface,
    },
    imagePreview: {
        width: '100px',
        height: '100px',
        objectFit: 'cover' as const,
        borderRadius: '6px',
        backgroundColor: colors.backgroundSecondary,
        marginTop: '4px',
    },
    actionsRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: '8px',
        marginTop: '4px',
        flexWrap: 'wrap' as const,
    },
    primaryActions: {
        display: 'flex',
        gap: '8px',
        flexWrap: 'wrap' as const,
    },
    primaryButton: {
        backgroundColor: colors.primary,
        color: colors.textInverse,
        border: 'none',
        padding: '6px 14px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: '13px',
        fontWeight: 500,
    },
    secondaryButton: {
        backgroundColor: colors.surface,
        color: colors.text,
        border: `1px solid ${colors.border}`,
        padding: '6px 12px',
        borderRadius: '6px',
        cursor: 'pointer',
        fontSize: '13px',
    },
    deleteTextButton: {
        backgroundColor: 'transparent',
        color: colors.danger,
        border: 'none',
        padding: '4px 0',
        cursor: 'pointer',
        fontSize: '12px',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '4px',
        whiteSpace: 'nowrap' as const,
    },
    modalOverlay: {
        position: 'fixed' as const,
        inset: 0,
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalBackdrop: {
        position: 'absolute' as const,
        inset: 0,
        backgroundColor: colors.overlay,
    },
    modalContent: {
        position: 'relative' as const,
        backgroundColor: colors.surface,
        borderRadius: '12px',
        maxWidth: '720px',
        width: '90%',
        maxHeight: '90vh',
        padding: '20px 24px',
        boxShadow: colors.boxShadows.modal,
        overflowY: 'auto' as const,
    },
    multiSelect: {
        border: `1px solid ${colors.border}`,
        borderRadius: '10px',
        padding: '8px 12px',
        backgroundColor: colors.surface,
        minHeight: '44px',
        boxShadow: colors.boxShadows.card,
    },
    multiSelectDropdownContainer: {
        borderRadius: '12px',
        border: `1px solid ${colors.border}`,
        backgroundColor: colors.surface,
        boxShadow: colors.boxShadows.card,
        padding: '6px',
    },
    multiSelectPlaceholder: {
        fontSize: '13px',
        color: colors.textMuted,
        fontWeight: 500,
    },
    multiSelectSelectedText: {
        fontSize: '13px',
        color: colors.text,
        fontWeight: 600,
    },
    multiSelectSearchInput: {
        border: `1px solid ${colors.border}`,
        borderRadius: '8px',
        padding: '8px 10px',
        fontSize: '13px',
        color: colors.text,
        backgroundColor: colors.backgroundSecondary,
    },
}), [colors]);

