import { Platform, StyleSheet } from 'react-native';

import type { ThemedColors } from '@/hooks/useTheme';

export const createStyles = (colors: ThemedColors) => StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  rootBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  containerMobile: {
    flexDirection: 'column',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 12,
  },
  sidebar: {
    width: 320,
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 18,
    padding: 8,
  },
  main: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: Platform.select({
      web: colors.surfaceMuted,
      default: colors.surface,
    }) as string,
    shadowColor: colors.shadows.heavy.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
    padding: 16,
    ...(Platform.OS === 'web' ? { overflow: 'auto' as any } : {}),
  },
  mainMobile: {
    padding: 12,
    borderRadius: 16,
    marginTop: 4,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 16,
  },
  heroRowMobile: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
  },
  heroTextBlock: {
    flex: 1,
    maxWidth: 480,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  heroSubtitle: {
    fontSize: 14,
    color: colors.textMuted,
  },
  heroButtonBlock: {
    minWidth: 200,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  topBarMobile: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  mobileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mobileFiltersHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  mobileFiltersLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  mobileFiltersResetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mobileSpinButton: {
    marginLeft: 8,
    flexShrink: 1,
  },
  resultsContainer: {
    flexGrow: 1,
    flexShrink: 0,
    paddingBottom: 32,
  },
  resultsContainerMobile: {
    paddingBottom: 16,
  },
  loaderBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loaderText: {
    marginTop: 12,
    color: colors.textMuted,
    fontSize: 14,
  },
  emptyBox: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    maxWidth: 360,
  },
  hintBox: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  hintTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 8,
  },
  hintText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    maxWidth: 380,
  },
  cardsGrid: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  cardsGridMobile: {
    paddingVertical: 8,
    paddingHorizontal: 0,
  },
  cardsContainer: {
    flexGrow: 1,
    flexShrink: 0,
    position: 'relative',
  },
  cardWrapper: {
    flex: 1,
    marginHorizontal: 8,
    marginBottom: 12,
  },
  rouletteWrapper: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 8,
    gap: 28,
  },
  // Группа: компас + центральная кнопка
  rouletteCompassGroup: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  // Компас — контейнер для изображения (вращается)
  rouletteCompassWrap: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: colors.borderLight,
    shadowColor: colors.shadows.heavy.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 10,
  },
  rouletteCompassImage: {
    width: '100%',
    height: '100%',
    borderRadius: 100,
  },
  // Кнопка поверх компаса
  rouletteCompassButton: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    shadowColor: colors.shadows.heavy.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    zIndex: 5,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' as any } : {}),
  },
  rouletteCompassButtonTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 2,
  },
  rouletteCompassButtonSubtitle: {
    fontSize: 10,
    color: colors.textMuted,
    textAlign: 'center',
  },
  // Ряд из 3 карточек под компасом
  rouletteCardsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    width: '100%',
    maxWidth: 960,
    flexWrap: 'wrap',
  },
  rouletteCard: {
    width: 280,
    maxWidth: '31%',
    minWidth: 240,
  },
  overlaySpinner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlayLight,
    zIndex: 1,
  },
  spinnerCircle: {
    minWidth: 220,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 999,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: colors.shadows.heavy.shadowColor,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 25,
  },
  spinnerText: {
    fontSize: 14,
    color: colors.textMuted,
  },
});
