import { Platform, StyleSheet } from 'react-native';

import type { ThemedColors } from '@/hooks/useTheme';

const nativeShadow = (
  colors: ThemedColors,
  height: number,
  opacity: number,
  radius: number,
  elevation?: number,
) => Platform.select({
  web: {
    boxShadow: colors.boxShadows.heavy,
  } as any,
  default: {
    shadowColor: colors.shadows.heavy.shadowColor,
    shadowOffset: { width: 0, height },
    shadowOpacity: opacity,
    shadowRadius: radius,
    ...(typeof elevation === 'number' ? { elevation } : {}),
  },
});

export const createStyles = (colors: ThemedColors) => StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  rootBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  containerMobile: {
    flexDirection: 'column',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 12,
  },
  sidebar: {
    width: 320,
    maxWidth: 360,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 18,
    padding: 8,
  },
  main: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: Platform.select({
      web: colors.surfaceMuted,
      default: colors.surface,
    }) as string,
    ...nativeShadow(colors, 10, 0.08, 24, 8),
    padding: 16,
    ...(Platform.OS === 'web' ? { overflow: 'auto' as any } : {}),
  },
  mainMobile: {
    padding: 12,
    borderRadius: 16,
    marginTop: 4,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 16,
  },
  heroRowMobile: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
  },
  heroTextBlock: {
    flex: 1,
    maxWidth: 480,
  },
  // В мобильной колонке (heroRowMobile) flex:1 с flexBasis:0 схлопывает блок
  // в нулевую высоту на native (Yoga), хотя web его растягивает по контенту
  heroTextBlockMobile: {
    flex: 0,
    flexBasis: 'auto',
    alignSelf: 'stretch',
    maxWidth: '100%',
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 4,
  },
  heroSubtitle: {
    fontSize: 14,
    color: colors.textMuted,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  topBarMobile: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  mobileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mobileFiltersHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  mobileFiltersLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.text,
  },
  mobileFiltersResetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mobileSpinButton: {
    marginLeft: 8,
    flexShrink: 1,
  },
  filtersModalShell: {
    flex: 1,
    backgroundColor: colors.background,
    ...Platform.select({
      web: {
        position: 'fixed',
        inset: 0,
        zIndex: 6000,
        minHeight: '100dvh',
        overflow: 'hidden',
      } as any,
    }),
  },
  resultsContainer: {
    flexGrow: 1,
    flexShrink: 0,
    paddingBottom: 32,
  },
  resultsContainerMobile: {
    paddingBottom: 16,
  },
  loaderBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loaderText: {
    marginTop: 12,
    color: colors.textMuted,
    fontSize: 14,
  },
  emptyBox: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.text,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    maxWidth: 360,
  },
  poolHint: {
    fontSize: 13,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: 12,
  },
  slotsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    width: '100%',
    maxWidth: 960,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  slotCard: {
    width: 280,
    maxWidth: '31%',
    minWidth: 200,
    height: 160,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.borderStrong,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  slotLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  cardsGrid: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  cardsGridMobile: {
    paddingVertical: 8,
    paddingHorizontal: 0,
  },
  cardsContainer: {
    flexGrow: 1,
    flexShrink: 0,
    position: 'relative',
  },
  cardWrapper: {
    flex: 1,
    marginHorizontal: 8,
    marginBottom: 12,
  },
  rouletteWrapper: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 8,
    gap: 28,
  },
  // Группа: компас + центральная кнопка
  rouletteCompassGroup: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  // Компас — контейнер для изображения (вращается)
  rouletteCompassWrap: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: colors.borderLight,
    ...nativeShadow(colors, 10, 0.12, 24, 10),
  },
  rouletteCompassImage: {
    width: '100%',
    height: '100%',
    borderRadius: 100,
  },
  mobileRoulettePrompt: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 260,
    paddingVertical: 24,
  },
  mobileRouletteCompassWrap: {
    width: 176,
    height: 176,
    borderRadius: 88,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: colors.borderLight,
    ...nativeShadow(colors, 8, 0.12, 20, 8),
  },
  // Кнопка поверх компаса
  rouletteCompassButton: {
    position: 'absolute',
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    ...nativeShadow(colors, 6, 0.15, 16),
    zIndex: 5,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' as any } : {}),
  },
  mobileRouletteCompassButton: {
    position: 'absolute',
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    ...nativeShadow(colors, 6, 0.15, 16),
    zIndex: 5,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' as any } : {}),
  },
  rouletteCompassButtonTitle: {
    alignSelf: 'stretch',
    fontSize: 11,
    fontWeight: '700',
    color: colors.text,
    textAlign: 'center',
    marginBottom: 2,
  },
  rouletteCompassButtonSubtitle: {
    alignSelf: 'stretch',
    fontSize: 10,
    color: colors.textMuted,
    textAlign: 'center',
  },
  // Ряд из 3 карточек под компасом
  rouletteCardsRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 20,
    width: '100%',
    maxWidth: 960,
    flexWrap: 'wrap',
  },
  rouletteCard: {
    width: 280,
    maxWidth: '31%',
    minWidth: 240,
  },
  overlaySpinner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.overlayLight,
    zIndex: 1,
  },
  spinnerCircle: {
    minWidth: 220,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 999,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    ...nativeShadow(colors, 10, 0.15, 25),
  },
  spinnerText: {
    fontSize: 14,
    color: colors.textMuted,
  },
});
