import { Platform, StyleSheet } from 'react-native';

import { DESIGN_TOKENS } from '@/constants/designSystem';

export const palette = DESIGN_TOKENS.colors;

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: palette.background,
  },
  rootBackgroundImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.9,
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 16,
  },
  containerMobile: {
    flexDirection: 'column',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 12,
  },
  sidebar: {
    width: 320,
    maxWidth: 360,
    backgroundColor: 'rgba(252,248,240,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(148,128,94,0.22)',
    borderRadius: 18,
    padding: 8,
  },
  main: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: Platform.select({
      web: 'rgba(255, 255, 255, 0.75)',
      default: 'rgba(255, 255, 255, 0.9)',
    }) as string,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 8,
    padding: 16,
  },
  mainMobile: {
    padding: 12,
    borderRadius: 16,
    marginTop: 4,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 12,
    gap: 16,
  },
  heroRowMobile: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 8,
  },
  heroTextBlock: {
    flex: 1,
    maxWidth: 480,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 4,
  },
  heroSubtitle: {
    fontSize: 14,
    color: palette.textMuted,
  },
  heroButtonBlock: {
    minWidth: 200,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  topBarMobile: {
    alignItems: 'stretch',
    flexDirection: 'column',
  },
  mobileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileFiltersButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(148,128,94,0.35)',
  },
  mobileFiltersHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  mobileFiltersLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: palette.text,
  },
  mobileFiltersResetButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  mobileSpinButton: {
    marginLeft: 8,
    flexShrink: 1,
  },
  resultsContainer: {
    flex: 1,
    paddingBottom: 32,
  },
  resultsContainerMobile: {
    paddingBottom: 16,
  },
  loaderBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  loaderText: {
    marginTop: 12,
    color: palette.textMuted,
    fontSize: 14,
  },
  emptyBox: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 6,
  },
  emptyText: {
    fontSize: 14,
    color: palette.textMuted,
    textAlign: 'center',
    maxWidth: 360,
  },
  hintBox: {
    paddingVertical: 32,
    alignItems: 'center',
  },
  hintTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: palette.text,
    marginBottom: 8,
  },
  hintText: {
    fontSize: 14,
    color: palette.textMuted,
    textAlign: 'center',
    maxWidth: 380,
  },
  cardsGrid: {
    paddingVertical: 12,
    paddingHorizontal: 4,
  },
  cardsGridMobile: {
    paddingVertical: 8,
    paddingHorizontal: 0,
  },
  cardsContainer: {
    flex: 1,
    position: 'relative',
  },
  cardWrapper: {
    flex: 1,
    marginHorizontal: 8,
    marginBottom: 12,
  },
  rouletteWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  rouletteCircle: {
    width: 520,
    height: 520,
    borderRadius: 260,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(148,128,94,0.35)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.08,
    shadowRadius: 32,
    elevation: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rouletteCard: {
    position: 'absolute',
    width: 290,
    maxWidth: '86%',
  },
  rouletteCardTop: {
    top: -124,
    left: '50%',
    transform: [{ translateX: -145 }, { translateY: -12 }, { rotate: '-8deg' }, { scale: 1 }],
  },
  rouletteCardLeft: {
    bottom: 0,
    left: -150,
    transform: [{ rotate: '-16deg' }, { scale: 0.96 }],
  },
  rouletteCardRight: {
    bottom: 0,
    right: -150,
    transform: [{ rotate: '16deg' }, { scale: 0.96 }],
  },
  rouletteCenter: {
    width: 190,
    height: 190,
    borderRadius: 95,
    borderWidth: 2,
    borderColor: 'rgba(148,128,94,0.45)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 20,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' as any } : {}),
  },
  rouletteCenterTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1f2933',
    textAlign: 'center',
    marginBottom: 4,
  },
  rouletteCenterSubtitle: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
  },
  rouletteCompassImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.85,
    borderRadius: 260,
  },
  overlaySpinner: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(248,248,248,0.45)',
    zIndex: 1,
  },
  spinnerCircle: {
    minWidth: 220,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 25,
  },
  spinnerText: {
    fontSize: 14,
    color: palette.textMuted,
  },
});
