import { Platform, StyleSheet } from 'react-native';
import { useMemo } from 'react';
import { DESIGN_TOKENS } from '@/constants/designSystem';
import { useThemedColors, type ThemedColors } from '@/hooks/useTheme';

export const getAboutStyles = (colors: ThemedColors) => StyleSheet.create({
  container: { flex: 1, width: '100%' },
  backgroundImage: { flex: 1, width: '100%', height: '100%', backgroundColor: colors.background },
  content: {
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
    paddingHorizontal: DESIGN_TOKENS.spacing.md,
    paddingVertical: DESIGN_TOKENS.spacing.lg,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
    paddingBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderAccent,
  },
  logoContainer: {
    marginBottom: 16,
  },
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  logoText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.textOnPrimary,
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    marginBottom: 12,
    color: colors.text,
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 18,
    color: colors.textMuted,
    textAlign: 'center',
    fontWeight: '500',
  },
  paragraph: {
    ...DESIGN_TOKENS.typography.scale.body,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.sm,
  },
  twoColumns: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: DESIGN_TOKENS.spacing.lg,
    alignItems: 'flex-start',
  },
  oneColumn: { flexDirection: 'column', gap: DESIGN_TOKENS.spacing.md },
  column: { flex: 1 },
  infoCard: {
    backgroundColor: colors.surface,
    borderRadius: DESIGN_TOKENS.radii.lg,
    padding: DESIGN_TOKENS.spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...Platform.select({
      web: {
        boxShadow: colors.boxShadows.card,
      },
      ios: {
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  cardHeader: {
    marginBottom: DESIGN_TOKENS.spacing.sm,
  },
  cardTitle: {
    ...DESIGN_TOKENS.typography.scale.h2,
    color: colors.text,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: DESIGN_TOKENS.spacing.md,
  },
  sectionTitle: {
    ...DESIGN_TOKENS.typography.scale.h3,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.sm,
  },
  stepsList: {
    gap: DESIGN_TOKENS.spacing.xs,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DESIGN_TOKENS.spacing.sm,
    paddingVertical: DESIGN_TOKENS.spacing.xs,
  },
  stepNumber: {
    width: 30,
    height: 30,
    borderRadius: DESIGN_TOKENS.radii.full,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.primaryAlpha30,
  },
  stepNumberText: {
    color: colors.primaryText,
    ...DESIGN_TOKENS.typography.scale.caption,
    fontWeight: '800',
  },
  stepText: {
    flex: 1,
    ...DESIGN_TOKENS.typography.scale.bodySmall,
    color: colors.text,
  },
  footerInfo: {
    marginTop: DESIGN_TOKENS.spacing.xs,
    gap: DESIGN_TOKENS.spacing.sm,
  },
  footerText: {
    ...DESIGN_TOKENS.typography.scale.bodySmall,
    color: colors.textMuted,
  },
  contactLabel: {
    ...DESIGN_TOKENS.typography.scale.bodyStrong,
    color: colors.text,
    marginTop: DESIGN_TOKENS.spacing.xs,
  },
  emailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DESIGN_TOKENS.spacing.xs,
    marginTop: DESIGN_TOKENS.spacing.xs,
    padding: DESIGN_TOKENS.spacing.sm,
    backgroundColor: colors.primarySoft,
    borderRadius: DESIGN_TOKENS.radii.md,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  emailButtonPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
  },
  emailText: {
    fontSize: DESIGN_TOKENS.typography.sizes.sm,
    color: colors.primaryText,
    fontWeight: '600',
    flexShrink: 1,
  },
  helperText: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textMuted,
  },
  linksBlock: {
    marginTop: DESIGN_TOKENS.spacing.xs,
    gap: DESIGN_TOKENS.spacing.xs,
  },
  socialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconLink: {
    width: 40,
    height: 40,
    borderRadius: DESIGN_TOKENS.radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.borderAccent,
  },
  iconLinkPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.98 }],
  },
  utilityLinksRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  textLink: {
    paddingVertical: DESIGN_TOKENS.spacing.xs,
    paddingHorizontal: DESIGN_TOKENS.spacing.sm,
    borderRadius: DESIGN_TOKENS.radii.sm,
    backgroundColor: colors.backgroundSecondary,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  textLinkPressed: {
    opacity: 0.75,
  },
  textLinkLabel: {
    fontSize: 13,
    color: colors.text,
    fontWeight: '600',
  },
  videoCard: {
    borderRadius: DESIGN_TOKENS.radii.lg,
    overflow: 'hidden',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 0,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 5,
  },
  videoCardHeader: {
    padding: DESIGN_TOKENS.spacing.md,
    paddingBottom: DESIGN_TOKENS.spacing.sm,
    backgroundColor: colors.primarySoft,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  videoCardTitle: {
    ...DESIGN_TOKENS.typography.scale.h3,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.xxs,
  },
  videoCardSubtitle: {
    fontSize: DESIGN_TOKENS.typography.sizes.sm,
    color: colors.textMuted,
    fontWeight: '500',
  },
  videoThumbWrap: {
    width: '100%',
    position: 'relative',
    aspectRatio: 16 / 9,
    backgroundColor: colors.backgroundTertiary,
  },
  videoThumb: {
    width: '100%',
    height: '100%',
    backgroundColor: colors.backgroundTertiary,
  },
  videoCardPressed: { opacity: 0.9, transform: [{ scale: 0.98 }] },
  playBadge: {
    width: 64,
    height: 64,
    borderRadius: DESIGN_TOKENS.radii.full,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -32,
    marginLeft: -32,
    shadowColor: colors.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  videoColumnMobile: { width: '100%', alignSelf: 'stretch' },
  videoCardFooter: {
    padding: DESIGN_TOKENS.spacing.sm,
    backgroundColor: colors.backgroundSecondary,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  videoCardFooterText: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 1,
  },
  contactSection: {
    marginTop: DESIGN_TOKENS.spacing.xl,
    paddingTop: DESIGN_TOKENS.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.borderAccent,
  },
  contactHeader: {
    marginBottom: DESIGN_TOKENS.spacing.lg,
    alignItems: 'center',
  },
  contactTitle: {
    ...DESIGN_TOKENS.typography.scale.h2,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.xs,
  },
  contactSubtitle: {
    ...DESIGN_TOKENS.typography.scale.bodySmall,
    color: colors.textMuted,
    textAlign: 'center',
  },
  form: {
    backgroundColor: colors.surface,
    borderRadius: DESIGN_TOKENS.radii.lg,
    padding: DESIGN_TOKENS.spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...Platform.select({
      web: {
        boxShadow: colors.boxShadows.light,
      },
      ios: {
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  input: {
    padding: DESIGN_TOKENS.spacing.sm,
    marginVertical: DESIGN_TOKENS.spacing.xs,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: DESIGN_TOKENS.radii.md,
    backgroundColor: colors.surface,
    fontSize: 16,
    color: colors.text,
    minHeight: DESIGN_TOKENS.touchTarget.minHeight,
    ...(Platform.OS === 'web' && {
      outlineStyle: 'none',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    }),
  },
  inputFocused: {
    borderColor: colors.primary,
    ...(Platform.OS === 'web' && {
      boxShadow: `0 0 0 3px ${colors.focus}`,
    }),
  },
  inputErr: {
    borderColor: colors.danger,
    backgroundColor: colors.dangerLight,
    borderWidth: 1.5,
  },
  message: {
    height: 108,
    textAlignVertical: 'top',
    minHeight: 108,
  },
  response: {
    textAlign: 'center',
    marginBottom: 20,
    fontSize: 16,
    padding: 12,
    borderRadius: 12,
    fontWeight: '500',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    padding: 10,
    backgroundColor: colors.dangerLight,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: colors.danger,
  },
  fieldErr: {
    color: colors.danger,
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  err: {
    color: colors.dangerDark,
    backgroundColor: colors.dangerLight,
    borderWidth: 1,
    borderColor: colors.danger,
  },
  ok: {
    color: colors.successDark,
    backgroundColor: colors.successLight,
    borderWidth: 1,
    borderColor: colors.success,
  },
  agreeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: DESIGN_TOKENS.spacing.sm,
    marginVertical: DESIGN_TOKENS.spacing.sm,
    padding: DESIGN_TOKENS.spacing.sm,
    minHeight: 48,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxMark: {
    color: colors.textOnPrimary,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: 'bold',
  },
  agreeLabel: {
    flex: 1,
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  agreeRowPressed: {
    opacity: 0.7,
    backgroundColor: colors.backgroundTertiary,
  },
  honeypot: { height: 0, opacity: 0, padding: 0, margin: 0 },
  socialSection: {
    marginTop: DESIGN_TOKENS.spacing.lg,
    paddingTop: DESIGN_TOKENS.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.borderAccent,
    alignItems: 'center',
  },
  socialTitle: {
    ...DESIGN_TOKENS.typography.scale.h3,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.md,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: DESIGN_TOKENS.spacing.sm,
    backgroundColor: colors.primarySoft,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.borderAccent,
    minWidth: 200,
    justifyContent: 'center',
  },
  socialButtonPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
    backgroundColor: colors.primaryLight,
  },
  socialIcon: {
    fontSize: 24,
  },
  socialText: {
    fontSize: 16,
    color: colors.primaryText,
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: colors.primary,
    paddingVertical: DESIGN_TOKENS.spacing.sm,
    paddingHorizontal: DESIGN_TOKENS.spacing.xl,
    borderRadius: DESIGN_TOKENS.radii.pill,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 52,
    ...Platform.select({
      web: {
        boxShadow: colors.boxShadows.medium,
      },
      ios: {
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  submitButtonDisabled: {
    backgroundColor: colors.disabled,
    shadowOpacity: 0,
    elevation: 0,
    opacity: 0.6,
  },
  submitButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  submitButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: colors.textOnPrimary,
    fontSize: DESIGN_TOKENS.typography.sizes.md,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  featuresSection: {
    marginTop: DESIGN_TOKENS.spacing.xl,
    paddingTop: DESIGN_TOKENS.spacing.xl,
    borderTopWidth: 1,
    borderTopColor: colors.borderAccent,
  },
  sectionHeader: {
    marginBottom: DESIGN_TOKENS.spacing.lg,
    alignItems: 'center',
  },
  featuresTitle: {
    ...DESIGN_TOKENS.typography.scale.h2,
    color: colors.text,
    marginBottom: DESIGN_TOKENS.spacing.xs,
    textAlign: 'center',
  },
  sectionSubtitle: {
    ...DESIGN_TOKENS.typography.scale.bodySmall,
    color: colors.textMuted,
    textAlign: 'center',
  },
  featureCard: {
    backgroundColor: colors.surface,
    borderRadius: DESIGN_TOKENS.radii.lg,
    padding: DESIGN_TOKENS.spacing.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    ...Platform.select({
      web: {
        boxShadow: colors.boxShadows.card,
      },
      ios: {
        shadowColor: colors.text,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  featureCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: DESIGN_TOKENS.spacing.xs,
    marginBottom: DESIGN_TOKENS.spacing.md,
    paddingBottom: DESIGN_TOKENS.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderAccent,
  },
  featureCardIcon: {
    fontSize: 28,
  },
  featureCardTitle: {
    ...DESIGN_TOKENS.typography.scale.h3,
    color: colors.text,
  },
  featureList: {
    gap: DESIGN_TOKENS.spacing.xs,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: DESIGN_TOKENS.spacing.xs,
    paddingVertical: DESIGN_TOKENS.spacing.xxs,
  },
  featureMark: {
    width: 24,
    height: 24,
    borderRadius: DESIGN_TOKENS.radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    marginTop: 1,
  },
  featureText: {
    flex: 1,
    ...DESIGN_TOKENS.typography.scale.bodySmall,
    color: colors.text,
  },
});

export const useAboutStyles = () => {
  const colors = useThemedColors();
  return useMemo(() => getAboutStyles(colors), [colors]);
};

export type AboutStyles = ReturnType<typeof getAboutStyles>;
