import { Platform, StyleSheet } from 'react-native';
import { DESIGN_TOKENS } from '@/constants/designSystem';

export const aboutStyles = StyleSheet.create({
  container: { flex: 1, width: '100%' },
  backgroundImage: { flex: 1, width: '100%', height: '100%', backgroundColor: '#fff' },
  content: {
    margin: 20,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 24,
    padding: 32,
    ...(Platform.OS === 'web' && {
      backdropFilter: 'blur(10px)',
      WebkitBackdropFilter: 'blur(10px)',
    }),
    ...Platform.select({
      web: {
        boxShadow: '0 24px 60px rgba(15, 23, 42, 0.10), 0 8px 24px rgba(15, 23, 42, 0.06)',
      },
      ios: {
        shadowColor: DESIGN_TOKENS.colors.text,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 24,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 40,
    paddingBottom: 24,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 159, 90, 0.2)',
  },
  logoContainer: {
    marginBottom: 16,
  },
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: DESIGN_TOKENS.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: DESIGN_TOKENS.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  logoText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: DESIGN_TOKENS.colors.surface,
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    marginBottom: 12,
    color: '#1f2937',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 18,
    color: '#6b7280',
    textAlign: 'center',
    fontWeight: '500',
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 26,
    color: '#374151',
    marginBottom: 16,
  },
  twoColumns: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 32,
    alignItems: 'flex-start',
  },
  oneColumn: { flexDirection: 'column', gap: 24 },
  column: { flex: 1 },
  infoCard: {
    backgroundColor: DESIGN_TOKENS.colors.surface,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    ...Platform.select({
      web: {
        boxShadow: '0 10px 26px rgba(15, 23, 42, 0.08)',
      },
      ios: {
        shadowColor: DESIGN_TOKENS.colors.text,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  cardHeader: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: DESIGN_TOKENS.colors.primary,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1f2937',
    letterSpacing: -0.3,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.08)',
    marginVertical: 24,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 20,
    letterSpacing: -0.2,
  },
  stepsList: {
    gap: 16,
  },
  stepItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 8,
  },
  stepNumber: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: DESIGN_TOKENS.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...Platform.select({
      web: {
        boxShadow: '0 10px 18px rgba(255, 159, 90, 0.28)',
      },
      ios: {
        shadowColor: DESIGN_TOKENS.colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  stepNumberText: {
    color: DESIGN_TOKENS.colors.surface,
    fontSize: 18,
    fontWeight: 'bold',
  },
  stepText: {
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
    color: '#374151',
    fontWeight: '500',
  },
  footerInfo: {
    marginTop: 8,
    gap: 16,
  },
  footerText: {
    fontSize: 14,
    lineHeight: 22,
    color: '#6b7280',
    fontStyle: 'italic',
  },
  contactLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1f2937',
    marginTop: 8,
  },
  emailButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
    padding: 12,
    backgroundColor: 'rgba(255, 159, 90, 0.1)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 159, 90, 0.2)',
  },
  emailButtonPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
  },
  emailIcon: {
    fontSize: 20,
  },
  emailText: {
    fontSize: 16,
    color: DESIGN_TOKENS.colors.primary,
    fontWeight: '600',
  },
  linksBlock: {
    marginTop: 12,
    gap: 10,
  },
  socialRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  iconLink: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 159, 90, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 159, 90, 0.16)',
  },
  iconLinkPressed: {
    opacity: 0.75,
    transform: [{ scale: 0.98 }],
  },
  utilityLinksRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 10,
  },
  textLink: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  textLinkPressed: {
    opacity: 0.75,
  },
  textLinkLabel: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '600',
  },
  videoCard: {
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: DESIGN_TOKENS.colors.surface,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    marginBottom: 16,
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    shadowColor: DESIGN_TOKENS.colors.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 5,
  },
  videoCardHeader: {
    padding: 20,
    paddingBottom: 16,
    backgroundColor: 'rgba(255, 159, 90, 0.05)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  videoCardTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  videoCardSubtitle: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  videoThumbWrap: {
    width: '100%',
    position: 'relative',
    aspectRatio: 16 / 9,
    backgroundColor: DESIGN_TOKENS.colors.text,
  },
  videoThumb: {
    width: '100%',
    height: '100%',
    backgroundColor: '#1a1a1a',
  },
  videoThumbWeb: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: Platform.OS === 'web' ? ('block' as any) : undefined,
  },
  videoCardPressed: { opacity: 0.9, transform: [{ scale: 0.98 }] },
  playBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 159, 90, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginTop: -40,
    marginLeft: -40,
    shadowColor: DESIGN_TOKENS.colors.text,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  playIconContainer: {
    marginLeft: 4,
  },
  playIcon: { color: DESIGN_TOKENS.colors.surface, fontSize: 32, fontWeight: 'bold' },
  videoColumnMobile: { marginTop: 24, width: '100%', alignSelf: 'stretch' },
  videoCardFooter: {
    padding: 16,
    backgroundColor: 'rgba(0,0,0,0.02)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
  },
  videoCardFooterText: {
    fontSize: 12,
    color: '#6b7280',
    textAlign: 'center',
    fontWeight: '500',
    letterSpacing: 1,
  },
  contactSection: {
    marginTop: 48,
    paddingTop: 32,
    borderTopWidth: 2,
    borderTopColor: 'rgba(255, 159, 90, 0.2)',
  },
  contactHeader: {
    marginBottom: 28,
    alignItems: 'center',
  },
  contactTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: DESIGN_TOKENS.colors.text,
    marginBottom: 8,
    letterSpacing: -0.4,
  },
  contactSubtitle: {
    fontSize: 16,
    color: DESIGN_TOKENS.colors.textMuted,
    textAlign: 'center',
  },
  form: {
    backgroundColor: DESIGN_TOKENS.colors.surface,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: DESIGN_TOKENS.colors.border,
    ...Platform.select({
      web: {
        boxShadow: '0 2px 8px rgba(31, 31, 31, 0.06), 0 1px 2px rgba(31, 31, 31, 0.04)',
      },
      ios: {
        shadowColor: '#1f1f1f',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  input: {
    padding: 16,
    marginVertical: 8,
    borderWidth: 2,
    borderColor: DESIGN_TOKENS.colors.border,
    borderRadius: DESIGN_TOKENS.radii.md,
    backgroundColor: DESIGN_TOKENS.colors.surface,
    fontSize: 16,
    color: DESIGN_TOKENS.colors.text,
    minHeight: 44,
    ...(Platform.OS === 'web' && {
      outlineStyle: 'none',
      transition: 'border-color 0.2s ease, box-shadow 0.2s ease',
    }),
  },
  inputFocused: {
    borderColor: DESIGN_TOKENS.colors.primary,
    ...(Platform.OS === 'web' && {
      boxShadow: `0 0 0 3px ${DESIGN_TOKENS.colors.focus}`,
    }),
  },
  inputErr: {
    borderColor: DESIGN_TOKENS.colors.danger,
    backgroundColor: DESIGN_TOKENS.colors.dangerLight,
    borderWidth: 1.5,
  },
  message: {
    height: 120,
    textAlignVertical: 'top',
    minHeight: 120,
  },
  response: {
    textAlign: 'center',
    marginBottom: 20,
    fontSize: 16,
    padding: 12,
    borderRadius: 12,
    fontWeight: '500',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 6,
    padding: 10,
    backgroundColor: DESIGN_TOKENS.colors.dangerLight,
    borderRadius: 8,
    borderLeftWidth: 3,
    borderLeftColor: DESIGN_TOKENS.colors.danger,
  },
  fieldErr: {
    color: DESIGN_TOKENS.colors.danger,
    fontSize: 13,
    fontWeight: '500',
    flex: 1,
  },
  err: {
    color: DESIGN_TOKENS.colors.dangerDark,
    backgroundColor: DESIGN_TOKENS.colors.dangerLight,
    borderWidth: 1,
    borderColor: DESIGN_TOKENS.colors.danger,
  },
  ok: {
    color: DESIGN_TOKENS.colors.successDark,
    backgroundColor: DESIGN_TOKENS.colors.successLight,
    borderWidth: 1,
    borderColor: DESIGN_TOKENS.colors.success,
  },
  agreeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginVertical: 12,
    padding: 12,
    backgroundColor: 'rgba(0,0,0,0.02)',
    borderRadius: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: DESIGN_TOKENS.colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DESIGN_TOKENS.colors.surface,
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: DESIGN_TOKENS.colors.primary,
    borderColor: DESIGN_TOKENS.colors.primary,
  },
  checkboxMark: {
    color: DESIGN_TOKENS.colors.surface,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: 'bold',
  },
  agreeLabel: {
    flex: 1,
    color: '#374151',
    fontSize: 14,
    lineHeight: 20,
  },
  agreeRowPressed: {
    opacity: 0.7,
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  honeypot: { height: 0, opacity: 0, padding: 0, margin: 0 },
  socialSection: {
    marginTop: 40,
    paddingTop: 32,
    borderTopWidth: 2,
    borderTopColor: 'rgba(255, 159, 90, 0.2)',
    alignItems: 'center',
  },
  socialTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 20,
    letterSpacing: -0.3,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    backgroundColor: 'rgba(255, 159, 90, 0.1)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 159, 90, 0.3)',
    minWidth: 200,
    justifyContent: 'center',
  },
  socialButtonPressed: {
    opacity: 0.7,
    transform: [{ scale: 0.98 }],
    backgroundColor: 'rgba(255, 159, 90, 0.15)',
  },
  socialIcon: {
    fontSize: 24,
  },
  socialText: {
    fontSize: 16,
    color: DESIGN_TOKENS.colors.primary,
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: DESIGN_TOKENS.colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 52,
    ...Platform.select({
      web: {
        boxShadow: '0 12px 24px rgba(255, 159, 90, 0.28)',
      },
      ios: {
        shadowColor: DESIGN_TOKENS.colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  submitButtonDisabled: {
    backgroundColor: '#d1d5db',
    shadowOpacity: 0,
    elevation: 0,
    opacity: 0.6,
  },
  submitButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.98 }],
  },
  submitButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: DESIGN_TOKENS.colors.surface,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  featuresSection: {
    marginTop: 48,
    paddingTop: 32,
    borderTopWidth: 2,
    borderTopColor: 'rgba(255, 159, 90, 0.2)',
  },
  sectionHeader: {
    marginBottom: 32,
    alignItems: 'center',
  },
  featuresTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 8,
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
  },
  featureCard: {
    backgroundColor: DESIGN_TOKENS.colors.surface,
    borderRadius: 20,
    padding: 28,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    ...Platform.select({
      web: {
        boxShadow: '0 10px 26px rgba(15, 23, 42, 0.08)',
      },
      ios: {
        shadowColor: DESIGN_TOKENS.colors.text,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  featureCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 24,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: DESIGN_TOKENS.colors.primary,
  },
  featureCardIcon: {
    fontSize: 28,
  },
  featureCardTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1f2937',
    letterSpacing: -0.3,
  },
  featureList: {
    gap: 16,
  },
  featureItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 4,
  },
  featureCheck: {
    fontSize: 20,
    color: '#10b981',
    fontWeight: 'bold',
    marginTop: 2,
    minWidth: 24,
  },
  featureComing: {
    fontSize: 20,
    color: DESIGN_TOKENS.colors.primary,
    fontWeight: 'bold',
    marginTop: 2,
    minWidth: 24,
  },
  featureText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 24,
    color: '#374151',
    fontWeight: '500',
  },
});

export type AboutStyles = typeof aboutStyles;
