import { StyleSheet, Platform } from 'react-native'

import type { useThemedColors } from '@/hooks/useTheme'
import { DESIGN_TOKENS } from '@/constants/designSystem'

export type CalendarStyles = ReturnType<typeof createCalendarStyles>

export function createCalendarStyles(colors: ReturnType<typeof useThemedColors>, isWideLayout: boolean) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    tabBar: {
      flexDirection: 'row',
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 4,
      gap: 8,
      flexWrap: 'wrap',
    },
    introCard: {
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: 4,
      padding: 16,
      borderRadius: DESIGN_TOKENS.radii.lg,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      gap: 8,
    },
    introBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    introBadgeText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textMuted,
    },
    introTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.text,
    },
    introDescription: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textMuted,
    },
    tabButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: DESIGN_TOKENS.radii.pill,
      borderWidth: 1.5,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : {}),
    },
    tabButtonActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    tabButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    tabButtonTextActive: {
      color: colors.surface,
    },
    contentLayout: {
      ...(isWideLayout
        ? {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: 16,
            paddingHorizontal: 16,
            paddingTop: 4,
          } as any
        : null),
    },
    calendarPane: {
      ...(isWideLayout ? { width: 360, flexShrink: 0 } as any : null),
    },
    listPane: {
      flex: 1,
      minWidth: 0,
      ...(isWideLayout ? { paddingTop: 0 } as any : null),
    },
    filterRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 8,
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 5,
      paddingHorizontal: 12,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.primaryLight,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    filterChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.primaryText,
    },
    listContent: {
      paddingHorizontal: 16,
      paddingBottom: 32,
      paddingTop: 4,
    },
    cardsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    cardWrap: {
      width: isWideLayout ? 'calc(33.333% - 8px)' as any : '100%',
      minWidth: isWideLayout ? 260 : undefined,
      marginBottom: 12,
      position: 'relative',
      ...(Platform.OS === 'web' ? { flexGrow: 0 } as any : null),
    },
    skeletonWrap: {
      padding: 16,
      gap: 16,
    },
    hint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginHorizontal: 16,
      marginTop: 4,
      marginBottom: 2,
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    hintText: {
      flex: 1,
      fontSize: 12,
      color: colors.textMuted,
      lineHeight: 15,
    },
    dateBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.primary,
      borderWidth: 1,
      borderColor: colors.primary,
      zIndex: 3,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: DESIGN_TOKENS.shadows.light,
            cursor: 'pointer',
          } as any
        : null),
    },
    emptyDateBadge: {
      backgroundColor: colors.surface,
      borderColor: colors.borderLight,
    },
    removeBadge: {
      position: 'absolute',
      top: 10,
      left: 10,
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      zIndex: 3,
      ...(Platform.OS === 'web'
        ? {
            boxShadow: DESIGN_TOKENS.shadows.light,
            cursor: 'pointer',
          } as any
        : null),
    },
    dateBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.surface,
    },
    emptyDateBadgeText: {
      color: colors.primaryText,
    },
    cardMetaStack: {
      gap: 3,
    },
    cardMetaContent: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 18,
    },
    cardMetaText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      flex: 1,
    },
    modalKeyboardAvoider: {
      flex: 1,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: Platform.OS === 'web' ? 'center' : 'flex-end',
      alignItems: Platform.OS === 'web' ? 'center' : 'stretch',
      padding: Platform.OS === 'web' ? 16 : 0,
    },
    modalSheet: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: DESIGN_TOKENS.radii.xl,
      borderTopRightRadius: DESIGN_TOKENS.radii.xl,
      paddingTop: 8,
      paddingHorizontal: 20,
      paddingBottom: Platform.OS === 'ios' ? 36 : 24,
      ...(Platform.OS === 'web'
        ? {
            width: 'min(520px, calc(100vw - 32px))',
            borderBottomLeftRadius: DESIGN_TOKENS.radii.xl,
            borderBottomRightRadius: DESIGN_TOKENS.radii.xl,
            boxShadow: DESIGN_TOKENS.shadows.heavy,
          } as any
        : null),
    },
    modalHandle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.borderLight,
      alignSelf: 'center',
      marginBottom: 16,
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.text,
      marginBottom: 6,
    },
    modalSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
      lineHeight: 18,
      marginBottom: 14,
    },
    statusEditorRow: {
      flexDirection: 'row',
      gap: 8,
      flexWrap: 'wrap',
      marginBottom: 14,
    },
    statusEditorOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
      ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : null),
    },
    statusEditorOptionText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    dateInput: {
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: DESIGN_TOKENS.radii.md,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 15,
      color: colors.text,
      backgroundColor: colors.background,
    },
    dateError: {
      fontSize: 12,
      color: colors.danger,
      marginTop: 6,
    },
    statusNoteBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: DESIGN_TOKENS.radii.md,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    statusNoteText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textMuted,
    },
    dateActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 14,
      flexWrap: 'wrap',
    },
    dateSecondaryButton: {
      flexGrow: 1,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: DESIGN_TOKENS.radii.pill,
      alignItems: 'center',
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    datePrimaryButton: {
      flexGrow: 1,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: DESIGN_TOKENS.radii.pill,
      alignItems: 'center',
      backgroundColor: colors.primary,
    },
    dateDangerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      width: '100%',
      marginTop: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: DESIGN_TOKENS.radii.pill,
      backgroundColor: colors.dangerLight,
      borderWidth: 1,
      borderColor: colors.danger,
      ...(Platform.OS === 'web' ? { cursor: 'pointer' } as any : null),
    },
    dateSecondaryText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    datePrimaryText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.surface,
    },
    dateDangerText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.danger,
    },
  })
}
